const createCardDatas = (img, love, career, health, money) => {
  return { img, love, career, health, money };
};

export const cardDetailDatas = [
  createCardDatas(
    '../img/TarotCard/0-The-Fool-Male.png',
    '-Nếu ở giai đoạn tìm hiểu. The Fool cứ ngỡ tình yêu là thế giới toàn màu hồng, không vội vã yêu mà bắt đầu mơ mộng về nửa kia của mình.<br/>-The Fool dường như hết mức ngây ngô đối với tình yêu. Trong chuyện tình cảm, ngay khi nửa kia thể hiện sự quan tâm lập tức họ vui sướng phát điên. Thật may mắn cho ai đó yêu được The Fool. Niềm đam mê thuần khiết, sự ngây thơ, chân thành không tính toán của họ là một món quà.<br/>-Mặc dù ở bên họ là một trải nghiệm thú vị. Nhưng khi ở trong một mối quan hệ lâu dài đôi khi sẽ trở thành một sự phiền phức.<br/>- Nếu muốn nâng tầm mối quan hệ, The Fool cần trang bị cho mình thêm thật nhiều kiến thức và kĩ năng về cuộc sống cho một hành trình dài hơi.<br/>',
    '-The Fool thể hiện một sự khởi đầu. Đề ra ý tưởng cũng như tính toán trong công việc. Giai đoạn này vẫn trong trạng thái hình thành tư tưởng. Xây dựng kế hoạch cho bản thân và vẽ ra viễn cảnh trong tương lai về 1 công việc đầy mơ ước. Nhìn chung viễn cảnh được vẽ ra một cách khá tích cực và ẩn chứa rất nhiều năng lượng nhiệt huyết, đam mê. Dám dấn thân nên mọi thứ bước đầu sẽ có tính khả quan. <br/>-Nhưng nhược điểm của The Fool là thiếu kinh nghiệm cũng như kĩ năng cần thiết. Vì vậy, cần phải nỗ lực cân bằng ý chí và khả năng để có thể có được quyết định đúng đắn nhất.<br/>-Đôi khi sự liều lĩnh, không cân nhắc kĩ sẽ dẫn tới tổn thất về mặt tài chính. Cần cẩn trọng trong việc chi tiêu, tránh việc quá mạo hiểm và liều lĩnh để hạn chế những rủi ro có thể.<br/>',
    '-Lá bài thể hiện sự lơ là của bạn trong việc chăm sóc bản thân. Sự hậu đậu và chủ quan sẽ khiến sức khỏe của bạn gặp nhiều biến động xấu. Lá bài ám chỉ sự suy sụp về sức khỏe và tinh thần có thể liên quan tới rượu hoặc chất kích thích. Bạn nên điều chỉnh lại thói quen sinh hoạt và kiềm chế bản thân trước các trò vui vô bổ, không bến bờ.<br/>',
    '-Lá bài thể hiện sự hoang phí đang diễn ra trong chi tiêu của bạn. Sự đầu tư hoặc chi trả cho các vấn đề của bạn đang thiếu sự chừng mực, sự đầu tư đó có thể là phục vụ cho đam mê của bạn nhưng nó đang ở mức độ phung phí cần điều chỉnh. Lá bài ám chỉ bạn nên xem xét lại kế hoạch chi tiêu của mình sao cho hợp lý.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/1-The-Magician.png',
    '-The Magician là một đối tượng hoàn hảo trong tình yêu. Họ hiểu rõ khả năng của mình và thực hiện một cách nhuần nhuyễn.<br/>-Phép thuật của The Magician sẽ mang 2 bạn lại gần nhau. Đó là sự hấp dẫn lẫn nhau, thấu hiểu vả thông cảm. The Magician còn báo hiệu rằng bạn hoàn toàn mê đắm đối phương.<br/>-Điểm cần khắc phục là The Magician có một cái tôi khá cao. Đôi khi chuyện tình cảm không phải là câu chuyện thắng thua. Nhưng là một người khôn khéo, mọi việc đều nằm trong tầm kiểm soát của Pháp Sư.<br/>',
    '-The Magician đại diện cho nhân vật đang học hỏi, tiếp nhận và vận dụng kĩ năng cần thiết cho công việc của mình.<br/>-Pháp Sư có sự khôn khéo, giỏi thích ứng đối với mọi khía cạnh trong công việc của mình. Có vẻ sự khôn khéo này sẽ giúp cho The Magician nhận được nhiều nguồn lực hỗ trợ về công việc cũng như công việc.<br/>-Lá bài nhấn mạnh việc cần trang bị cho mình kĩ năng khi muốn đạt được mục tiêu cũng như thăng tiến trong công việc.<br/>',
    '-Lá bài cho biết mọi sự quyết tâm của bạn sẽ mang đến áp lực không nhỏ. Bạn sẽ rơi vào tình trạng lo lắng, bệnh tật có thể đến bạn nên có sự chuẩn bị. Sự chuẩn bị tâm lý và sức khỏe ngay từ lúc ban đầu sẽ giúp bạn dễ dàng ứng phó với những khó khăn. Thể lực có thể bị ảnh hưởng, căng thẳng có thể dẫn đến những trận ốm dai dẳng.<br/>-Nên chú ý tới các gói bảo hiểm để đề phòng trường hợp xấu xảy ra. The Magician đưa ra lời khuyên bạn nên chăm chỉ tập luyện, giữ tâm lý vui vẻ, lắng nghe tiếng nói của bản thân để đẩy lùi bệnh tật.<br/>',
    '-The Magician cho thấy dấu hiệu của sự sung túc và giàu có. Bạn sẽ không phải lo ngại về các vấn đề tài chính, các nguồn thu sẽ dồi dào. Tuy nhiên, lá bài cũng cho thấy bạn sẽ bị mất mát nếu vay mượn. Rất nhiều phi vụ làm ăn với lợi nhuận hấp dẫn sẽ đến, hết sức cẩn thận và tỉnh táo để không quyết định sai lầm. Nguồn tài chính cá nhân sẽ tăng lên nhưng nguy cơ của sự mất mát cũng tăng, nên bảo quản tốt tiền bạc để tránh thất thiệt.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/2-The-High-Priestess.png',
    '-The High Priestess ám chỉ một người nội tâm và nhạy cảm.<br/>-Mặc dù vậy họ không hề yếu đuối, Nàng biết cách điều khiển cảm xúc và kiến thức của bản thân. Nếu bạn đang định bắt đầu một mối quan hệ mới , The High Priestess đề cao trực giác của bạn.<br/>-Hãy đánh giá lại người bạn quan tâm. Bạn cần cảm nhận đối phương bằng nội tâm.<br/>-The High Priestess đại diện cho sự khôn ngoan và cả sự thanh thản. Sâu trong tiềm thức nàng sẽ tìm ra vấn đề và giải quyết đúng lúc.<br/>',
    '-The High Priestess là sự đào sâu về mặt chuyên môn. Lời khuyên của lá bài này là hoạch định kế hoạch tốt. Chau dồi khả năng chuyên môn, học hỏi phải có sự chọn lọc các yếu tố tốt xấu để đối phó những công việc xảy ra sau này. <br/>-ương ứng về vấn đề tài chính, The High Priestess thể hiện sự học hỏi về việc sử dụng những nguồn lực tài chính hiệu quả nhất.<br/>-The High Priestess còn nhắc nhở rằng cân nhắc trước khi đưa ra quyết định. Trong giai đoạn ẩn chứa những nguy hiểm tiềm tàng, cần nâng cao bản lĩnh và kiến thức để vượt qua trở ngại. The High Priestess còn thể hiện sự tiếp thu tri thức từ những bậc tiền bối<br/>',
    '-Lá bài với hình ảnh nữ tu huyền bí nhắc nhở bạn nên chăm sóc những người phụ nữ trong gia đình và chính bản thân mình nếu bạn là nữ giới.<br/>-Sự che giấu của lá bài báo hiệu những hiểm họa về sức khỏe có thể xảy đến, quan tâm chăm sóc sức khỏe của chính bạn và người thân là việc cấp thiết ngay lúc này.<br>',
    '-Lá bài đại diện cho sự chắc chắn trong chi tiêu. Các khoản tài chính của bạn đang dần ổn định, kế hoạch thắt chặt chi tiêu đang có những hiệu quả tốt. Đây cũng là lúc các khoản vay mượn của bạn trở nên dễ dàng.<br/>-Tuy nhiên, sự chủ quan sẽ gây ra hậu quả đáng tiếc. Mọi hoạt động vay mượn, ký kết của bạn nên có giấy tờ chứng thực rõ ràng dựa vào sự thỏa thuận giữa hai bên.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/3-The-Empress.png',
    '-The Empress là hình ảnh người mẹ. Đó là một người phụ nữ lí tưởng trong gia đình, không phải trong tình yêu. Sự ân cần, quan tâm chăm sóc và chăm sóc mọi thứ chỉn chu giúp bạn ghi điểm trong mắt mọi người.<br/>-Nhưng đôi khi sự hoàn hảo của bạn là áp lực rất lớn với đối phương. Và đối với những đối tượng chua đủ chín chắn, hiểu được giá trị, họ sẽ không nhìn ra sự tuyệt vời của bạn.<br/>-Nhưng The Empress đại diện cho sư chung thủy. Đối với họ sẽ không có chuyện bắt cá hai tay, hay lừa dối. Đối với gia đình The Empress sẵn sàng hi sinh những lợi ích cá nhân để chăm lo gia đình.<br/>-Nhưng đôi khi họ phải chú ý tới bản thân và chiều chuộng mình để giữ được sự chú ý của đối phương lâu dài<br/>',
    '-với tính chất của The Empress ta nhận ra lá bài này thể hiện sự tích cực và an toàn trong công việc. Lá The Empress thể hiện sự gia tăng, phát triển khuyến khích bạn đưa ra kế hoạch nhằm tiếp tục phát triển. Một ý tưởng tốt, kế hoạch tốt sẽ thu lại được những kết quả tích cực.<br/>-Khi gặp The Empress tròn trải bài về công việc, cần nhanh chóng nắm bắt thời cơ này. Bạn nên tranh thủ tối đa những nguồn lực, sự ủng hộ để đạt được những ưu thế. Và bạn cần giữ vững những phẩm chất khiến mọi người tin tưởng để tiếp tục nhận được những sự hậu thuẫn.<br/>-Các lời tiên đoán về The Empress đều thể hiện trạng thái vui vẻ hợp tác với đồng nghiệp. Và công việc cũng như sự nghiệp của bạn sẽ có bước tiến triển tốt.<br/>',
    '-The Empress mang đến tín hiệu tốt về tình trạng sức khỏe của bạn. Nếu bạn đang bị bệnh và nhận điều trị thì thời điểm này bệnh tình sẽ có những khởi sắc, bạn sẽ sớm khỏe mạnh trở lại nếu chăm sóc kỹ lưỡng.<br/>-Nếu bạn thường xuyên mỏi mệt, bực dọc lời khuyên là bạn nên nghỉ ngơi, cho bản thân những khoảng không gian thư giãn riêng, tránh làm việc quá sức.<br/>-Đi du lịch hoặc tham gia các hoạt động ngoại khóa ngắn hạn rất có ích để cải thiện tâm trạng và thể lực.<br/>',
    '-Lá bái thông báo thời cơ thích hợp cho những phi vụ đầu tư. Đây là lúc bạn không nên đắn đo quá lâu trước các quyết định liên quan tới tiền bạc để tránh bỏ lỡ cơ hội. Bạn có thể thoải mái trong vấn đề đi vay mượn và cho vay mượn, The Empress mang ý nghĩa dự báo những khoản đầu tư sẽ sinh lời mạnh mẽ.<br/>-Tuy nhiên, lá bài mang đến sự cảnh báo về sự phung phí. Nếu bạn đang sở hữu một khoản tài chính lớn nhưng không có kế hoạch đầu tư và sử dụng hợp lý thì tình trạng tiêu pha phung phí sẽ xảy ra.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/4-The-Emperor.png',
    'The Emperor là người có quyền lực tối cao. Sự kiêu ngạo và tự tôn chính là điểm yếu của họ trong tình yêu. Dù có tình cảm với đối với đối phương, cách quan tâm của họ cũng rất độc đáo. Họ sẽ tìm cách gây ảnh hưởng đến đối phương nhưng không để lộ tình cảm của mình.<br/>-Nhưng The Emperor là người có tính ổn định và cẩn trọng. Nên trong một mối quan hệ đặc biệt quan trọng, họ sẽ thể hiện sự quan tâm một cách âm thầm, lặng lẽ. Và cũng vì cao ngạo nên họ không thể hiện một cách cuồng nhiệt thái quá. <br/>-Nhưng ta luôn có thể tin tưởng về tính chung thủy, ổn định của The Emperor. Họ luôn có chuẩn mực đạo đức cao và truyền thống. Đôi khi ta sẽ thấy lá bài xuất hiện với cương vị người Cha, họ sẽ ảnh hưởng tới mối quan hệ tình cảm của bạn.<br/>',
    '-Khi gặp The Emperor trong trải bài liên quan đến công việc sẽ là một dấu hiệu tích cực. Có vẻ bạn đã tính toán kĩ càng, những ý tưởng được thể hiện vững vàng, chắc chắn và định hình được kết quả. Nhưng bạn cần giữ được thái độ ôn hòa dù đã có tính toán kĩ lưỡng.<br/>-The Emperor còn biểu thị cho quyền hành, ưu thế lớn trong đàm phán. Bạn có thể giữ vững địa vị và ứng phó với những rắc rối phát sinh. Trong đàm phán bạn cần lắng nghe những ý kiến bổ ích để đảm bảo thắng lợi toàn diện.<br/>-The Emperor thường kiểm soát tốt những vấn đề về tài chính và có khả năng làm việc độc lập. Nhưng chính vì vậy lời khuyên ở đây là không nên tự mãn về thành quả cũng như bản thân. Và khi công việc gặp phải những khó khăn, cần phải giữ vững nỗ lực và mục tiêu của mình.<br/>',
    '-The Emperor mang đến cảnh báo về những dấu hiệu lạ trên cơ thể. Nếu bạn cảm thấy có gì bất thường nên đi kiểm tra ngay. Vì những tham vọng trong công việc bạn sẽ bị áp lực và mệt mỏi hãy tăng cường các hoạt động tốt cho sức khỏe như thể dục, gym, đi bộ và thiền. Sự cẩn trọng trong tính cách sẽ giúp bạn nhận ra sự quan trọng của sức khỏe.<br/>',
    '-Ý nghĩa của The Emperor mách bảo rằng nếu bạn không muốn bị mất tiền oan thì nên cẩn thận trước các mối kinh doanh, hợp đồng béo bở. Sự thận trọng cần được đặt lên trên tất cả, bạn nên tuân theo các nguyên tắc quen thuộc, tránh sáng tạo hoặc bạo dạn đi một con đường mới vì đây không phải thời điểm lý tưởng.',
  ),
  createCardDatas(
    '../img/TarotCard/5-The-Hierophant.png',
    '-The Hierophant là một người chuẩn mực, truyền thống. Trong tình yêu cũng vậy, tính truyền thống đối với bạn là những giá trị vô giá. Một mối quan hệ truyền thống, phù hợp với các chuẩn mực đạo đức xã hội luôn thu hút bạn.<br/>-Khi theo đuổi đối phương, bạn thường theo mô tuýp cổ điển. Bao gồm : tìm hiểu kĩ càng, xây dựng sự tin tưởng, quan tâm, hẹn hò, thỉnh thoẳng tặng quà. Tuy không quá dồn dập nhưng khiến đối phương không thể quên.<br/>-Trong tình yêu, The Hierophant biểu hiện đây là một tình yêu dựa trên giá trị và niềm tin chung. Sự xuất hiện của lá bài cho thấy sự hài hòa trong mối quan hệ. Cả hai cùng ý thức rõ ràng về trách nhiệm và cố gắng vun đắp tình cảm.<br/>',
    '-The Hierophant mô tả nhân vật nắm quyền lực về mặt tinh thần. Lá bài chỉ ra những yếu tố mới lạ và ở phạm vi rất rộng so với hiểu biết của bạn. Nếu muốn đưa ra được những hoạch định cụ thể, cần có lời khuyên của người giỏi hơn. Xây dựng nhưng mối quan hệ dựa trên sự hòa hợp về tư tưởng để đưa ra những phương án tốt nhất.<br/>-Lời khuyên của The Hierophant trong công việc là bạn cần tập trung học hỏi những kinh nghiệm. Và tích cực mở rộng mối quan hệ và bạn sẽ nhận ra người thầy của mình.<br/>-Trong đầu tư và kinh doanh, lá bài khuyên bạn nên chọn lựa đối tác cẩn thận trong vấn đề tài chính. Một mối quan hệ hòa hợp về mặt tinh thần sẽ là ưu tiên số một cho bạn thời điểm này.<br/>',
    '-The Hierophant thông báo rằng bạn không nên bỏ sót bất cứ dấu hiệu lạ nào từ cơ thể. Sự thách thức từ công việc có thể khiến bạn suy sụp cùng tâm lý bất an, những bài thể dục nhẹ, tâm sự cùng người lớn tuổi hơn sẽ giúp cải thiện tình hình. Nếu bạn đang bị bệnh thì những niềm tin vào tôn giáo, tín ngưỡng có thể tạo ra chuyển biến tốt.<br/>',
    '-Mọi sự đầu tư và tiêu pha lúc này không mang lại may mắn như bạn nghĩ. The Hierophant khuyên bạn nên chi tiêu theo thói quen cũ, nguyên tắc cần được đặt ra để duy trì sự ổn định. <br/>-Đây không phải thời điểm tốt để đầu tư và mua bán, mọi thứ liên quan đến tiền bạc cần được quản lý chặt chẽ. Các mối kinh doanh hấp dẫn có thể mời chào, bạn không nên mạo hiểm với những điều mới lạ.<br/>-Nếu muốn đầu tư, vay mượn nên xin ý kiến tư vấn của chuyên gia hoặc người có kinh nghiệm. Bạn có thể gặp bất chắc về tài chính nếu mạo hiểm làm mọi thứ một mình.<br>',
  ),
  createCardDatas(
    '../img/TarotCard/6-The-Lovers.png',
    '- Con người ta thường dẽ dàng ngộ nhận tình cảm. Yêu thích ai đó thì dễ nhưng có một tình yêu đích thực thì rất khó. Tình yêu của The Lover là một tình yêu thực sự, lâu dài và bền vững.<br/>-Vậy nên bạn không nên vội vàng mà hãy chậm rãi chờ đợi một người thích hợp. Và nếu gặp họ , bạn thực sự rất may mắn. Cả hai đều hướng về nhau với tình cảm chân thật nhất.<br/>-he Lover nói rằng cả hai đều bị thu hút về nhau một cách sâu sắc. Nhưng cả hai đều chậm rãi tìm hiểu để chắc chắn về tình cảm và thể hiện mình coi trọng đối phương. Dường như cả hai sẽ bước vào một mối quan hệ nghiêm túc.<br/>-The Lover là sự đồng điệu giữa hai tâm hồn, hài hòa ở cấp độ cao nhất. Đây là một tình yêu không vụ lợi toan tính và sẽ bền vững lâu dài.<br/>',
    '-lá bài thể hiện rất rõ chủ đề tình cảm. Hiển nhiên là khi yêu thì cuộc sống của chúng ta nhất định bị chi phối. Có thể dẫn tới sự thay đổi kế hoạch. Việc dựa hoàn toàn vào tình cảm, bỏ qua yếu tố khác là việc làm thừa nhiệt huyết nhưng thiếu khôn ngoan.<br/>-Cần có sự kiểm tra và điều chỉnh kế hoạch trước khi thực hiện. Sự quyến rũ, vẻ đẹp, tình yêu của The Lover khiến bạn bị cuốn hút vào tình yêu.<br/>-Đôi khi mục đích của bạn cũng có thay đổi nhằm hướng tới những mong muốn tình cảm. Cần giữ một tinh thần tỉnh táo trong chi tiêu liên quan đến vấn đề tình cảm. Tránh chi tiêu quá nhiều theo cảm hứng nhất thời. Và tình yêu cũng là trạng thái tích cực và là nguồn động lực phát triển tài chính.<br/>',
    '- The Lovers mang ý nghĩa rằng bạn đang có vấn đề về sức khỏe, hãy tìm đến bác sĩ để nhận được lời tư vấn. Bạn không nên tự ý đoán bệnh và uống thuốc theo ý muốn để tránh gặp vấn đề. Vì là lá bài về tình yêu và sự đam mê nên cảnh báo của The Lovers cũng liên quan đến tình ái. Hãy cẩn thận hết sức vì bạn có thể mắc một vài căn bệnh liên quan tới tình ái.<br/>',
    '- Bạn sẽ nhận được những món tiền từ người thân trong gia đình hoặc bạn bè chí cốt. Mọi nỗ lực của bạn đang được đền đáp xứng đáng bằng những thành công về vật chất.<br/>-Cảnh báo từ The Lovers là không nên cho người khác vay mượn tiền, đặc biệt là bạn thân vì sự mất lòng trong quan hệ của cả hai có thể xảy ra. Nếu bạn đang muốn xoay vốn để kinh doanh hoặc bắt đầu xây dựng một nền tảng công việ mới hãy tìm đến các mối các quan hệ thật sự tin cậy, họ sẽ dốc sức giúp đỡ bạn.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/7-Chariot.png',
    '- The Chariot mang bản tính thích chinh phục. Mục tiêu càng khó thì họ càng có hứng thú. Đôi khi tính hiếu thắng lại mang tính phá hoại trong tình yêu. Thật đáng tiếc khi thời nay hầu hết người trẻ tuổi luôn mang một tâm lí hiếu thắng như vậy.<br/>- Mang tâm lý chinh phục, The Chariot sẽ tận dụng mọi thế mạnh để được sự ưu ái của đối phương. Cách thức của họ rất đa dạng, nhưng đôi khi sự háo thắng chưa chắc đã là tình yêu. <br/>-Nhưng khi bước vào một mối quan hệ lâu dài, The Chariot biểu thị cho khả năng cân bằng. Họ có đủ nghị lực để duy trì mục tiêu. Họ biết cách thể hiện mong muốn và đáp ứng được nhu cầu của tình yêu.<br/>- Đôi khi The Chariot còn là dấu hiệu bạn đang bị kiểm soát bởi đối phương. Họ là người quan tâm chăm sóc đối phương cũng như gánh vác, chia sẻ. Tuy đôi lúc họ cứng rắn, khó thỏa hiệp nhưng chỉ là họ quan tâm bạn quá mức mà thôi.<br/>',
    '-The Chariot trong chủ đề công việc thể hiện sự điều hành, quản lí. Được dự đoán về tính chiến thắng, thành công. Bạn được mô tả đã vượt qua được nút thắt khó khăn và có những tính toán đúng đắn. Lời khuyên là cần có sự phối hợp tốt các kỹ năng của mình trong hoạch định kế hoạch. <br/>-The Chariot cũng mô tả bản lĩnh của nhân vật, đã có sự thăng tiến và nắm vững nguyên tắc.Cần cẩn trọng tối đa trước khi đầu tư tài chính vào một việc nào đó. Nên cân nhắc những phương án dự phòng cũng như sự phân bố tiền bạc.<br/>-The Chariot thể hiện một chuyển đổi quan trọng trong việc quản lí, kiểm soát các vấn đề vật chất, thực tế. Bên cạnh sự cứng rắn để duy trì sự ổn định thì bạn cần có sự mềm dẻo, linh hoạt. Và đó cũng là nghệ thuật quản lí nhằm giúp bạn dễ dàng loại bỏ những cản trở trong công việc.<br/>',
    '- The Chario khuyên bạn nên dành thời gian nhiều hơn cho bản thân và gia đình. Thiên nhiên trong lành sẽ giúp bạn khỏe mạnh hơn, các buổi Yoga hay thiền là ý kiến hay.<br/>-Lá bài còn cảnh báo bạn tránh xa các chất kích thích và thức khuya. Sức khỏe có thể suy yếu do thói quen sinh hoạt thiếu lành mạnh và thời gian làm việc thiếu khoa học.<br/>',
    '- Lá bài The Chariot là lá bài tốt về mặt tài chính, tuy nhiên bạn đang chi tiêu thiếu chừng mực. Nếu bạn cần vay mượn và xoay vốn để đầu tư kinh doanh thì đây là lúc khá thích hợp nhưng nếu bạn đang định cho vay thì nên xem xét. <br/>-Nên xem xét tình hình tài chính và khả năng hoàn tiền của người đi vay để đưa ra mức cho vay hợp lý, tránh rủi ro và rạn nứt tình cảm. Lá bài còn khuyên bạn nên dành thời gian cho những chuyến nghỉ dưỡng để tinh thần được thư giãn.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/8-Strength.png',
    '- Lá Strength trong tình yêu ngược hẳn với tên gọi. Họ là một người khá yếu đuối và nhẫn nại. Họ mong muốn có một tình yêu mà đối phương có thể để bạn dựa vào. Tuy nhiên sự rụt rè quá mức khi chưa bước vào một mối quan hệ sẽ đánh mất cơ hội của bạn. <br/>-Strength nói đến một người nhu hòa, tâm tính mềm mại, nhẫn nại, dịu dàng. Khi theo đuổi ai đó, họ sẽ từ từ chăm chút mà ngần ngại nói ra tình cảm của mình. Họ hy vọng đối phương sẽ nhận ra tình cảm của mình. Sự ân cần thể hiện tình cảm chân thật của bạn khiến đối phương cảm động.<br/>-Tuy nhiên sự nhẫn nại của bạn đôi khi quá mức. Trong tình yêu đôi khi hãy để làn sóng đam mê của bạn được nổi dậy. Nó sẽ tiếp thêm sức mạnh cho mối quan hệ của bạn tiến lên.<br/>',
    '- Với chủ đề sức mạnh Strength đưa ra lời tiên đoán về lòng can đảm. Bạn cần phải có sự dũng cảm trong việc đưa ra những hoạch định đối với những khó khăn. Cần tập trung những nguồn lực mình có vào kế hoạch, khó khăn trước mắt. Cân nhắc kĩ trước khi đưa ra quyết định cuối cùng và cần có dũng khí thực hiện nó. Càng gần tới thành công tính chất khó khăn của công việc càng thể hiện.<br/>-Strength có sức mạnh để đối đầu. Kiên trì đến cùng theo đuổi điều mình đã xác định, khẳng định con đường đúng đắn của mình. Khi tiến hành đầu tư, đừng chỉ nghĩ trực tiếp tới khoản tiền thu về.<br/>-Thay vào đó Strength đưa ra lời khuyên hành động vì đam mê. Nó sẽ dẫn đường cho thành công kéo theo nguồn lợi về tiền bạc một cách chân chính. Hãy phát huy sức mạnh của bản thân.<br/>',
    '- Sự bận rộn của công việc khiến bạn không có nhiều thời gian riêng tư để chăm sóc sức khỏe. Các chế độ ăn uống giảm đạm và chất béo sẽ giúp bạn thanh lọc cơ thể. <br/>-Tránh mọi sự căng thẳng không cần thiết, bạn nên đến phòng tập gym nhiều hơn để cơ thể dẻo dai, ít ốm vặt. Nếu bạn đang bị bệnh thì hãy kiên trì và tin tưởng vào bác sĩ, lá bài Strength báo hiệu bạn sẽ sớm bình phục.<br/>',
    '- Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br/>-Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br>- Tuy nhiên, bạn nên cẩn thận trước lời mời gọi hợp tác hấp dẫn. Mọi kiến nghị quá hoàn hảo từ phía đối tác có thể là cái bẫy lớn chờ bạn nhảy vào, sự tỉnh táo và quyết đoán sẽ giúp bạn thoát khỏi tình huống này nhưng sự cảnh giác chưa bao giờ là thừa thãi.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/9-The-Hermit.png',
    '- The Hermit tượng trưng cho một con người cô độc. Dường như họ chỉ muốn sống một cuộc đời độc thân, tránh xa những phức tạp của tình yêu, hôn nhân, gia đình. Họ thích sự tự do của mình, đối với họ tình yêu không quá quan trọng.<br/>-ho dù The Hermit động tâm với một người khác, họ cũng không thừa nhận. Tâm thế cao ngạo cũng là một trở ngại với họ. Theo đuổi một người tuýp như The Hermit tuyệt đối rất vất vả.<br/>.Khi trong một mối quan hệ, ta thấy sự xuất hiện của The Hermit là ta sẽ thấy một sự bế tắc. Nó nói đến một sự tạm ngưng chia sẻ của một mối quan hệ. Ngay cả khi trong một mối quan hệ lâu dài, họ cũng cần rất nhiều không gian riêng.<br/>.Đôi khi bạn sẽ tủi thân khi trong mối quan hệ với The Hermit. Họ khá vô tâm và thờ ơ, lạnh nhạt với đối phương<br/>',
    '- The Hermit tượng trưng cho chủ đề trí tuệ, khôn ngoan và thận trọng. Vì vậy, nếu bạn đang cân nhắc bắt đầu một dự án công việc thì lá bài sẽ dành cho bạn những lời khuyên. Không nên quá phô trương, cần phải đưa ra những hoạch định và hành động cẩn thận, kín đáo. Đôi khi sự phô trương sẽ thu hút nhiều sự chú ý, khó khăn cho công việc của bạn.<br/>=Chủ đề của The Hermit còn là về tiềm thức. Lời khuyên là bạn cần tập trung, giữ được sự ổn định trong tinh thần, tránh bị dao động. Để đạt tới bản lĩnh này không hề dễ dàng. Cần xác định được mục đích cao nhất mà mình muốn theo đuổi, tập trung nguồn lực tài chính. Kiên trì theo đuổi và không nản chí khi gặp phải một số khó khăn nhất thời.<br/>',
    '- Đây là thời gian bạn hay bị ốm do sự thay đổi của môi trường sống. Thời tiết nắng mưa đột ngột khiến bạn rơi vào những cơn ốm dai dẳng không dứt, hạn chế ra ngoài và che chắn cẩn thận nếu bắt buộc phải di chuyển để bảo vệ sức khỏe. Nếu bạn đang điều trị thì lá bài The Hermit nói rằng sự an ủi, động viên từ phía gia đình cùng những người bạn thân thiết sẽ giúp bạn vượt qua được thời gian khó khăn này.<br/>',
    '- Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br/>-Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br>- Tuy nhiên, bạn nên cẩn thận trước lời mời gọi hợp tác hấp dẫn. Mọi kiến nghị quá hoàn hảo từ phía đối tác có thể là cái bẫy lớn chờ bạn nhảy vào, sự tỉnh táo và quyết đoán sẽ giúp bạn thoát khỏi tình huống này nhưng sự cảnh giác chưa bao giờ là thừa thãi.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/10-The-Wheel-of-Fortune.png',
    '- Với ai đang tìm kiếm tình yêu, Wheel Of Fortune là dấu hiệu tốt ám chỉ bạn sắp gặp được đối tượng. Cơ hội có thể đến rất bất ngờ và kì lạ, đây có thể là một bước ngoặt tốt.<br/>- Nếu bạn đang quen người như Wheel Of Fortune, họ sẽ mang luồng sinh khí mới mẻ tràn đầy sức sống. Mọi cảm xúc của bạn sẽ lạ lẫm nhưng không hề tiêu cực. Người này sẽ thay đổi bạn và cuộc sống theo một cách tích cực hơn.<br/>- Đôi khi Wheel Of Fortune là dấu hiệu của một sự thay đổi trong mối quan hệ. Bạn cần xác định được những thay đổi đó có ý nghĩa như thế nào và thích nghi với những thay đổi đó.<br/>',
    '-Wheel Of Fortune là lời tiên đoán về những chu kì liên hoàn và vận may trong công việc. Lời khuyên là bạn cần có sự tiếp xúc với thế giới xung quanh, bám sát vấn đề. Trong hoạch định của bạn cần phân tích để hiểu về hoàn cảnh cũng như mục đích của mình.<br/>-Wheel Of Fortune nói đến những thay đổi những cơ hội đi kèm những khó khăn. Điểm tích cực trong lá bài là hầu hết ý nghĩa đều chỉ ra vận may, hạnh phúc. Bạn cần phát hiện ra thời cơ và đầu tư tài chính của mình một cách nhanh chóng. Những cơ hội như vậy không dễ xuất hiện lần thứ 2. Cần có sự tích trữ về tài chính để chuẩn bị cho sự thay đổi lớn lao sắp tới.<br/>',
    '-Duy trì các thói quen không lành mạnh sẽ khiến sức khỏe của bạn xuống dốc, bạn nên thử thay đổi bản thân theo chiều hướng tích cực hơn. Các buổi tập hoặc bài vận động nhẹ tăng sự sảng khoái, tỉnh táo là điều cần thiết.<br/>-Nếu bạn đang trong giai đoạn khám chữa bệnh thì lá bài The Wheel of Fortune khuyên rằng nên lưu ý tới các tác nhân đến từ bên ngoài để tránh tình trạng sức khỏe trở nên tồi tệ.<br/>',
    '-Lá bài The Wheel of Fortune mang lại may mắn về tiền bạc. Nếu bạn đang rỗng túi thì lá bài là tín hiệu thông báo bạn sắp dư dả trở lại trong thời gian ngắn. Trường hợp bạn đang có kinh tế tốt thì lá bài nhắc nhở bạn nên tiêu tiền một cách có chủ đích, sự phung phí sẽ khiến bạn nhanh chóng “tiền khô cháy túi”. Ngoài ra, việc xuất hiện của The Wheel of Fortune còn tượng trưng cho việc những trò chơi, vụ cá cược sẽ mang lại may mắn cho bạn <br/>',
  ),
  createCardDatas(
    '../img/TarotCard/11-Justice.jpg',
    '-Justice chỉ ra bạn rất tìm kiếm đối tượng, việc này sẽ mất khá nhiều thời gian. Bạn dự định tình yêu sẽ đến một mối quan hệ lâu dài. Bạn sẽ kiên trì chờ đợi người phù hợp. Việc yêu đương nhăng nhít giờ với bạn không phù hợp nữa.<br/>-Và khi xác định được tình cảm của mình rồi Justice vẫn chưa vội vàng. Lí do bạn không vội vàng là vì banh muốn xác định một mối quan hệ nghiêm túc. Bạn cẩn thận cân nhắc xem đối phương có tình cảm với mình không và muốn một mối quan hệ lâu dài không. <br/>-Ưu điểm của Justice là sự nghiêm túc. Justice còn chỉ về hôn nhân hợp pháp. Đồng thời nó còn chỉ ra sự cân bằng trong mối quan hệ của hai bạn. Họ luôn tìm cách tránh xung đột để cân bằng cuộc sống hôn nhân.<br/>',
    '-Justice thể hiện hình ảnh một người đang cố gắng điều chỉnh để giữ gìn công lý. Điều hướng vào việc nỗ lực nhằm giữ gìn cân bằng trong hoạch định hướng đi. Bạn cần xem xét kĩ những hoạch định trước khi thực hiện.<br/>-Justice lưu ý tính khả thi cũng như cân bằng giữa các phần của kế hoạch. Cần phải có sự thận trọng trong hành động của mình. Bạn có kĩ năng và dùng nó thiết lập trật tự nhưng đôi khi bạn cần phải giữ được hòa khí trong các mối quan hệ. Đôi khi bạn cần cân bằng mối quan hệ đồng nghiệp nhưng vẫn phải đảm bảo công bằng và sự thật<br/>-Khi đang có ý định đầu tư, Justice nhắc nhở bạn cần phải có sự cân nhắc dựa trên kinh nghiệm của mình. Cần cố gắng giữ được sự cân bằng trong đầu tư tài chính, nếu không chắc chắn bạn hãy tạm ngưng kế hoạch đầu tư.<br/>',
    '-Sự áp lực từ công việc và mối quan hệ tình cảm khiến bạn ngột thở. Lá bài Justice thông báo rằng bạn đang cần tìm lại sự cân bằng trong cuộc sống. Những buổi du lịch ngắn ngày hoặc nghỉ mát ở đâu đó gần nhà sẽ giúp bạn ổn định hơn. Nếu bạn đang ốm dài ngày thì lá bài dự báo chuỗi ngày ốm yếu sẽ sớm được kết thúc, bạn nên kiên trì sử dụng thuốc để bệnh sớm hồi phục.<br/>',
    '-Những thành quả lao tâm khổ sức suốt thời gian qua có thể nhận về những tín hiệu đáng mừng. Tuy nhiên, lá bài Justice nói rằng nếu bạn có liên quan tới các hoạt động kinh doanh buôn bán phi pháp thì bạn sẽ bị truy tố về mặt pháp lý. Mặt khác, sẽ có một khoản tiền về với tay bạn có thể do khoản thừa kế.<br/>-Lời khuyên của lá bài là trong thời điểm này mọi quyết định liên quan tới tiền bạc nên được cân nhắc kỹ càng, các hợp đồng đầu tư béo bở sẽ đến nhưng bạn phải cẩn thận để không dính vào hoạt động kinh doanh phi pháp.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/12-The-Hanged-Man.jpg',
    '- The Hanged Man có vẻ đang khao khát một mối quan hệ với người trong lòng. Nhưng có vẻ đối phương không quan tâm cho lắm. Tình cảm này dường như là đơn phương.<br/>-Việc yêu một người quá lâu dù không được đáp lại đã trở thành một thói quen. Họ cứ chờ đợi và bên cạnh đối phương. Đôi khi đã quá quen với cảm giác này họ cho rằng cứ ở bên cạnh đối phương là họ mãn nguyện. Tuy nhiên sớm muộn The Hanged Man sẽ hối hận về quyết định của mình. <br/>- Đôi khi The Hanged Man là tình trạng treo lơ lửng của tình yêu. Bạn không thể kiểm soát được nhưng cũng không thể từ bỏ. Nhưng kéo dài tình trạng này không phải là cách hay, cần học cách đối mặt.<br/>',
    '- The Hanged Man thể hiện chủ đề đi tìm tri thức. Ngoài ra lá bài còn đưa ra lời tiên tri về sự hy sinh, mất mát như dự đoán về biến cố ngoài ý muốn. Nên bạn cần định hình lại các hoạch định, đừng quá quan tâm đến lợi ích và thua thiệt trước mắt. Hãy biết chấp nhận những thất bại tạm thời.<br/>-The Hanged Man đưa ra lời khuyên thay đổi bản thân, nâng cao tri thức và bản lĩnh. Thất bại và khó khăn là điều kiện thiết yếu cho sự phát triển sự nghiệp lâu dài. <br/>- The Hanged Man còn nhắn nhủ bạn rằng tách mình ra khỏi vấn đề tiền bạc. Cho bạn thời gian để cân nhắc và đưa ra quyết định chính xác về tiền bạc, tránh tổn thất kéo dài. Đôi khi việc dừng lại đúng lúc là lựa chọn khó khăn nhưng đúng đắn.<br/>',
    '-Bạn có thể gặp một vài biến cố về sức khỏe trong thời điểm này. Nên nhớ rằng không gì tồn tại mãi mãi, sức trẻ và sự dẻo dai của bạn đang bị ảnh hưởng bởi những áp lực xung quanh.<br/>-Hãy tìm đến bác sĩ để nhận được lời khuyên có ích. Lá bài The Hanged Man khuyên rằng bạn nên ăn uống lành mạnh, tập luyện thường xuyên để cơ thể khỏe mạnh<br/>',
    '-Lá bài The Hanged Man nói rằng giai đoạn hiện tại không phải thời cơ sinh lợi nhuận trong kinh doanh. Mọi hoạt động kinh doanh cần được kiểm soát nghiêm ngặt.<br/>-Hình ảnh người đàn ông bị treo ngược trong lá bài The Hanged Man đại diện cho sự hoang mang của bạn, các hoạt động kinh doanh sẽ không có tiến triển nhiều dù bạn đã dốc sức.<br/>-Lời khuyên là bạn nên thực hiện chậm rãi các bước từ nghiên cứu thị trường đến nghiên cứu khách hàng để đạt hiệu quả kinh doanh. Nếu bạn định nhảy việc thì hãy cân nhắc vì đây chưa chắc là quyết định sáng suốt.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/13-Death.jpg',
    '-Nếu bạn đã kết thúc một mối quan hệ đã lâu thì Death cho rằng bạn hãy mở cánh cửa trái tim mình. Sự kết thúc luôn đi đôi với một khởi đầu mới. Đã đến lúc bạn cho người khác cũng như bản thân mình cơ hội để đón nhận hạnh phúc. Nếu bạn đang trong quá trình tìm hiểu và nhận thấy sự phù hợp.<br/>-Death biểu thị nên kết thúc quá trình này để tới thời điểm có một mối quan hệ chính thức. Death không đáng sợ như tên gọi trong trường hợp này.<br/>-Nhưng khi Death xuất hiện khi hai bạn gặp rắc rối trong một mối quan hệ, tình yêu này đã đến lúc từ bỏ. Có thể tình cảm của hai người đã không còn như lúc đầu.<br/>-Death cũng là dấu hiệu cảnh tỉnh mối quan hệ của hai người. Nếu muốn mọi thứ tốt lên bạn cần có cách thức thích hợp<br/>',
    '-Death thể hiện sự kết thúc, chuyển đổi từ con đường cũ sang con đường mới. Bạn có thể sẽ tiếp tục trượt dài trên sự thất bại và có thể là sự kết thúc công việc.<br/>Bạn cần phải có sự tin tưởng vào bản thân vượt qua thất bại để thay đổi hiện tại. Bạn cần sẵn sàng cho sự thay đổi và dứt khoát với những cái cũ, lạc hậu. Sẵn sàng chấp nhận những tổn thất hiện tại để thực hiện sự thay đổi.<br/>-Death trong đầu tư và kinh doanh là dấu hiệu của những tổn thất và thất bại trong một số dự án bạn đầu tư. Những thất bại này sẽ giúp bạn nhận ra được bản chất của vấn đề và sẽ có sự sáng suốt trong tương lai.<br/>-Bạn cần thay đổi cung cách làm việc và đầu tư sao cho phù hợp.<br/>',
    '-Tình trạng sức khỏe của bạn đang diễn biến theo chiều hướng xấu, nếu bạn đang điều trị có thể bệnh sẽ nặng thêm. Nếu bạn đang bình thường thì dấu hiệu bị bệnh sẽ ngày một rõ ràng đến khi bạn phát giác, bạn thường xuyên căng thẳng. Nên đi kiểm tra sức khỏe định kỳ để phát hiện ra những vấn đề một cách sớm nhất, đừng bỏ qua những dấu hiệu bất thường.<br/>-Lời khuyên lá bài Death mang đến là tinh thần phấn chấn cùng sự tin tưởng vào tôn giáo sẽ giúp bạn vượt qua giai đoạn này. Lúc này những người thân bên cạnh sẽ là nguồn động viên, an ủi cực kỳ có ích với bạn. Không nên quá lo lắng vì đây là giai đoạn buộc phải trải qua.<br/>',
    '-Tình hình tài chính sau một thời gian dài bị thâm hụt đang có những bước khởi sắc mới. Nếu bạn đang có điều kiện khá tốt, lá bài dự đoán sẽ có những thay đổi về mặt tài chính diễn ra trong thời gian tới. Lúc này, mọi sự cố vấn từ người có chuyên môn sẽ giúp ích rất nhiều cho việc cân đối thu chi.<br/>-Tín hiệu rõ ràng nhất mà lá bài Death mang đến là giai đoạn này sẽ có một số thay đổi lớn về mặt tiền bạc, có thể bạn sẽ nhận được một nguồn tiền sau nhiều ngày cạn kiệt cũng có thể bạn phải bỏ ra một khoản chi phí lớn. Nhìn chung, lá bài mang đến một sự thay đổi lớn và bạn phải học cách thích nghi.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/14-Temperance.jpg',
    '-Temperance thể hiện sự nỗ lực mang lại sự cân bằng tương ứng vận dụng quyền lực. Bạn cần lắng nghe những người có liên quan khi muốn hoạch định. Và cần đảm bảo lợi ích hài hòa cho các bên.  <br/>-Trong vấn đề hợp tác và đàm phán, Temperance khuyên chúng ta tận dụng các nguồn lực để tạo ra thế cân bằng. Về đầu tư tài chính, bạn cần thêm đối tác hoặc người hỗ trợ. Những sự giúp đỡ, trợ giúp đắc lực để có thể lèo lái những kế hoạch theo ý mình. Bạn sẽ đạt được thành tựu về tài chính hiệu quả nhất. <br/>-Nếu có sự cạnh tranh trong công việc Temperance khuyên bạn cân nhắc kĩ lưỡng. Mục đích quan trọng là công việc nhưng cũng cần cân bằng những mối quan hệ.<br/>',
    '-Nếu bạn đang độc thân, Temperance nói rằng bạn luôn cố gắng cân bằng mọi thứ. Bạn đang trì hoãn chuyện yêu đương vì sợ sẽ gây mất cân bằng trong cuộc sống và ảnh hưởng đến mục tiêu của bạn. <br/>-Hoặc nếu bạn đang phân vân giữa 2 người, Temperance nói rằng cả hai đều có tình cảm với bạn. Nhưng nếu bạn cứ mãi cân nhắc, họ sẽ mất kiên nhẫn. Và tệ hơn sự thiếu quyết đoán sẽ khiến bạn chẳng có ai bên cạnh.<br/>-Nếu bạn đang trong mối quan hệ lâu dài, có thể bạn đang gặp khó khăn lớn trong việc cân bằng. Có thể tình yêu của hai bạn gặp phải sự phản đối của gia đình, bạn bè, hoặc người thân.<br/>-Temperance đang nỗ lực cân bằng. Bạn luôn thể hiện mình nhẫn nại nhưng không phải lúc nào cũng thành công.<br/>',
    '-Công việc rất quan trọng nhưng sức khỏe của bản thân mới là thứ vô giá. Bạn đang cần cân bằng giữa công việc và sức khỏe.  <br/>-Nếu bạn đang bị bệnh và nhận điều trị thì lá bài Temperance cho rằng các hoạt động thể dục và tập luyện ngắn sẽ phát huy tác dụng tốt. Mọi sự nghỉ ngơi tại thời điểm hiện tại đều là sự cần thiết, bạn không nên quá tham vọng mà quá sức.<br/>',
    '-Lá bài Temperance ám chỉ bạn đang mất cân bằng trong chi tiêu. Có những khoản chi tiêu không cần thiết bạn cần tiết chế, mọi quyết định đầu tư và mua bán đều cần suy nghĩ cẩn thận. Nếu bạn đang có ý định muốn đề xuất tăng lương thì đây là thời điểm phù hợp.  <br/>-Lá bài Temperance  thông báo rằng bạn nên xem xét lại năng lực bản thân để đề xuất mức lương cao hơn, thực tế bạn có tinh thần làm việc hăng say và sự hy sinh hết mình vì công việc.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/15-The-Devil.jpg',
    '-The Devil đại diện cho cám dỗ về tình dục. Tất nhiên, tình dục là một nhu cầu thiết yếu của con người. Tình dục là sự thăng hoa của tình yêu lên một cung bậc mới. Nhưng tình dục không có tình yêu chỉ khiến con người ta trở nên phàm tục, trần trụi.<br/>-The Devil thể hiện một người chăm chăm vào sự thỏa mãn thể xác, đam mê tình dục. <br/>-The Devil tự tin tràn ngập, cho rằng không ai có thể thoát khỏi sự thu hút của mình. Việc chinh phục và nhiều chiến tích khiến The Devil say sưa. Nhưng bạn sẽ sớm hối hận về những quyết định của mình.<br/>-Nếu đang trong một mối quan hệ The Devil còn thể hiện sự lệ thuộc, không thể thoát ra. Bạn cho phép mình bỏ lí trí qua một bên, tình nguyện tiếp tục mối quan hệ. Cho dù biết rằng có vấn đề nhưng bạn không cam tâm từ bỏ nó.<br/>',
    '-The Devil với chủ đề cám dỗ về tiền bạc, quyền lực, vật chất và nỗi ám ảnh về nỗi sợ hãi mất đi. <br/>-Lời khuyên là bạn cần hiểu rõ bản thân mình mong muốn gì và theo đuổi đúng hướng. Tránh để bị lôi kéo, dụ dỗ vào những việc xấu vì những lợi ích xa hoa không thực. Khi cảm thấy có những khúc mắc mình không thể giải quyết thì bạn cần tìm đến một người đáng tin cậy và có kinh nghiệm. <br/>-Trong vấn đề tiền bạc khi xuất hiện The Devil bạn luôn cần thận trọng. Cần tìm một tấm gương trên con đường tâm linh để có thể dễ dàng hơn trước những khó khăn. Đôi khi sự mù quáng khiến bạn sa lầy một cách tệ hại. Cần tìm một chỗ dựa đáng tin cậy về tâm linh, nó sẽ kéo bạn ra khỏi vũng lầy.<br/>',
    '-The Devil mang đến cả tín hiệu tích cực và tiêu cực liên quan tới sức khỏe. Phần lớn những vấn đề về sức khỏe sẽ diễn ra trong thời gian tới. Bạn có thể ốm đau và nhận điều trị, tuy nhiên bạn khá chán nản và buông xuôi.<br/>-The Devil khuyên bạn nên lấy lại tinh thần, sự an ủi và quan tâm của người thân sẽ giúp bạn vượt qua giai đoạn khó khăn này. Đôi khi The Devil lại mang lại tín hiệu tích cực, nếu bạn đã ốm dài ngày thì lá bài cho biết thời gian này đã sắp chấm dứt.<br/>',
    '-Tiền bạc là phương tiện quyết định sự thành bại nhưng sự thực dụng quá mức có thể khiến bạn đánh mất bản thân. <br/>-The Devil đưa ra tín hiệu rằng bạn nên kiểm soát tiền bạc, tuyệt đối không để tiền bạc kiểm soát cuộc sống. Bí quyết thành công trong công việc là tâm huyết và sáng suốt, mọi hành động mờ ám, nịnh nọt sớm muộn cũng bị phát giác.<br/>-Lá bài The Devil cảnh cáo sự khéo léo và hành động lươn lẹo của một số người sẽ làm bạn bị lừa dối, hãy cảnh giác cao độ. Những vấn đề về tiền và tài chính có thể diễn ra trong thời gian tới sẽ khiến bạn chán nản.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/16-The-Tower.jpg',
    '-Nếu The Tower xuất hiện khi bạn vẫn đang độc thân, nó nói răng bạn chưa sẵn sàng cho tình yêu. Những khía cạnh thay đổi khiến bạn cảm thấy không tin tưởng vào tình yêu. Và bạn thấy cuộc sống độc thân mang tới sự an toàn cho bạn hơn. <br/>-Và khi The Tower xuất hiện khi bạn đang trong giai đoạn mới tìm hiểu về một người về chuyện tình cảm. Nó báo hiệu bạn có vẻ chưa quen với tình trạng này dù có thích đối phương. Sẽ mất một thời gian để bạn chấp nhận họ<br/>-The Tower còn mang tới lời cảnh báo về sự thay đổi trong tình yêu. Nó có thể đến từ bên ngoài nhưng cũng có thể đến từ chính đối phương của bạn. Bạn sẽ cảm thấy khá sốc nhưng cần mạnh mẽ để đối mặt với nó. Càng né tránh câu chuyện sẽ càng tồi tệ hơn.<br/>',
    '-Sự xung đột, tai họa không lường trước, tiêu cực là lời tiên đoán đầu tiên của The Tower. Bạn cần có sự tỉnh táo trong công việc. Tránh gây ra những mâu thuẫn trong những mối quan hệ làm ảnh hưởng đến công việc. Có thể trong nội bộ có những bất hòa, có những người không vừa lòng và tìm cách lừa dối phản bội bạn. <br/>-Tránh sự lệ thuộc vào tình cảm quá nhiều trong những mối quan hệ. Bạn không thể biết được sự thay đổi tính cách của con người. <br/>-The Tower còn đưa ra lời cảnh báo cẩn trọng trong những quyết định về tiền bạc. Không nên giao phó cho những người bạn không tin tưởng. Tránh những dự định mang tính phiêu lưu, cảm tính.<br/>-The Tower khuyên bạn nên thoát ra những mối quan hệ mang lại rắc rối.<br/>',
    '-Những sự tan vỡ và sụp đổ sẽ khiến bạn mất sức, bạn gần như chán nản và muốn buông xuôi mọi thứ. <br/>-The Tower thông báo sự đổ vỡ không chỉ về mặt thể chất mà tinh thần cũng ảnh hưởng không kém. Việc cần làm hiện tại không gì khác ngoài nghỉ ngơi, nếu bạn mất đi sức khỏe mọi sự còn lại đều không có ý nghĩa gì. <br/>-Thay vì chán nản, ủ rũ tại sao không ra ngoài dạo phố, ăn uống và tận hưởng thời gian xả hơi này. Nên tránh xa các chất kích thích và gây nghiện vì thời gian suy sụp này dễ khiến bạn dính vào các tệ nạn và thói quen xấu.<br/>',
    '-Thời điểm này, những rắc rối xoay quanh công việc và những khoản chi phí phát sinh sẽ khiến bạn eo hẹp về kinh tế. <br/>-Nếu bạn đang muốn đầu tư kinh doanh một sản phẩm mới thì nên cân nhắc kỹ bởi đây không phải là thời điểm thuận lợi. <br/>-Nếu sự nghiệp của bạn đang trong thời kỳ hưng thịnh thì nên chuẩn bị tinh thần và tiền bạc kỹ lưỡng vì The Tower dự báo những sóng gió nguy nan sắp đến sẽ khiến bạn rơi vào tình trạng khó khăn.<br/>-Các thành quả bạn gây dựng có thể bị tiêu tán, mọi công sức có thể đổ bể nên hãy chuẩn bị tinh thần để đối phó với các vấn đề này.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/17-The-Star.jpg',
    '-Nếu bạn vẫn cứ đang mãi không dám bắt đầu một mối quan hệ. The Star nói rằng bạn đang nhìn thấy thực tại về tình yêu thời đại này. Dường như nó mất đi sự mơ mộng, thuần khiết vốn có. Con người đang hướng tới những mối quan hệ thỏa mãn những vật chất họ mong muốn. Và họ quên mất rằng, có những thứ còn tệ hơn cả thiếu thốn vật chất.<br/>-Khi bạn đang trong tìm hiểu, The Star chỉ ra rằng người kia đang tiếp cận bạn vì một giá trị lợi dụng nào đó. Và khi trong một mối quan hệ lâu dài, có thể có quá nhiều rắc rối vây quanh bạn. <br/>-The Star biểu hiện cho sự hy vọng và lạc quan. Hiện giờ có thể rất khó để bình tĩnh với nhau, The Star khuyên bạn im lặng. Hãy nhìn nhận lại toàn bộ mối quan hệ một cách khách quan và cho nó tương lai.<br/>',
    '-The Star thể hiện sự chủ động trong kiểm soát và quản lí công việc.<br/>-Bạn cần cố gắng xem xét lại mọi mặt của vấn đề và nhìn rộng hơn. Hãy sử dụng những mối quan hệ và sự giúp đỡ để thiết lập kế hoạch tốt cho công việc. Bạn không nên chỉ nhìn tới lợi ích cá nhân mà cần một cái nhìn xa và rộng hơn. <br/>-The Star mang đến niềm hy vọng và viễn cảnh tươi sáng. Lời khuyên ở đây là bạn cần nhanh chóng ổn định lại tinh thần của mình. Mọi chuyện chỉ thuận lợi hơn khi tinh thần của bạn yên bình nhất. Trải qua những kinh nghiệm của biến cố trước, bạn cần nhìn nhận vấn đề rõ ràng hơn. Và biết cách tận dụng những nguồn lực để khôi phục trạng thái ổn định về tiền bạc và tương lai<br/>',
    '-Lá bài như một ngôi sao hy vọng, các vấn đề về sức khỏe sẽ được cải thiện. Những cơ hội kinh doanh cứ liên tục đến khiến bạn phải làm việc quá sức, cần đề phòng cơn đột quỵ đột ngột. <br/>-Nghỉ ngơi là điều cần làm nhất, khám định kỳ theo quý hoặc năm sẽ giúp bạn phòng ngừa và điều trị kịp thời. Nếu bạn đang phải chịu đựng bệnh tật và cơn đau thì The Star mang đến tin vui với việc điều trị, sự hy vọng cùng tinh thần lạc quan là điều duy nhất giúp bạn thoát khỏi bệnh tật.<br/>',
    '-Những cơ hội kinh doanh béo bở sẽ mang lại cho bạn một khoản tiền lớn. Những kế hoạch đầu tư khá thuận lợi, đối tác kinh doanh cũng đưa ra những điều khoản có lợi cho bạn. Các dự án mới, hợp đồng mới là các cơ hội kiếm tiền hấp dẫn trong giai đoạn này. <br/>-Tuy nhiên, mọi chuyện quá suôn sẻ có thể là dấu hiệu của sự lừa đảo. Hãy cẩn trọng với các cơ hội đòi hỏi đầu tư quá nhiều vốn hoặc nguồn lợi nhuận khủng. The Star cũng nhắc nhở chế độ chi tiêu cần khoa học hơn, sự phung phí và khoe khoang về sức mạnh tài chính sẽ mang đến hiểm họa.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/18-The-Moon.jpg',
    '-The Moon là một lời đoán về sự ảo tưởng.<br/>-Khi bắt đầu tìm hiểu hay dành tình cảm cho ai đó, bạn thường đắm chìm trong mộng tưởng của mình. Bạn ảo tưởng về tình cảm của mình dành cho đối phương mặc dù chưa có đủ sự thấu hiểu. Đồng thời, bạn cũng có ảo tưởng về người kia cũng có tình cảm dành cho mình. Và nó sẽ khiến bạn ngày càng rời xa hiện thực và ảnh hưởng tiêu cực.<br/>-Còn khi đang trong một mối quan hệ, The Moon chỉ ra rằng bạn có một lo lắng ở sâu bên trong tiềm thức. Bạn có một nỗi bất an.<br/>-The Moon là một lá bài tâm linh. Nó còn chỉ ra có những việc bị che dấu sắp được sáng tỏ. Bạn đã lờ đi những cảnh báo về tâm thức của mình. Trực giác đã cố cảnh báo nhưng bạn đã cật lực lờ nó đi.<br/>',
    '-The Moon mang sức mạnh huyền bí và sự thường biến dự đoán giai đoạn này rất bất định.<br/>-Những kế hoạch của bạn vì vậy mà cũng bị ảnh hưởng. Bạn cần nỗ lực đưa ra kế hoạch của mình. Có thể sẽ có nhiều khó khăn và cả thất bại nhưng cũng cần phải giữ vững lập trường. Tránh bị lôi kéo bởi những ý tưởng không thực, suy xét thật kĩ trước khi đưa ra ý kiến. <br/>-Đôi khi The Moon còn chỉ ra sự ảo tưởng, lẫn lộn và khủng hoảng về tinh thần. Bạn cần giữ được sự bình tĩnh và khôn ngoan để mình bị dẫn dụ vào những kế hoạch hão huyền. Đôi khi bạn còn phải học cách chấp nhận thất bại. Nhưng đừng vì vậy mà bạn trở nên nản lòng.<br/>-Ngoài ra cũng cần lưu ý đề phòng những người có ý định lừa gạt làm ảnh hưởng đến tiền bạc của bạn.<br/>',
    '-Sự thư giãn và nghỉ ngơi trong giai đoạn này là điều cần thiết. Sau những nỗ lực với các rắc rối bạn trở nên kiệt sức. Những áp lực từ cuộc sống, công việc thậm chí cả trong mối quan hệ tình cảm khiến bạn căng thẳng.<br/>-Sự nghỉ ngơi là hết sức cần thiết trước khi tình trạng xấu đi. Khi có những dấu hiệu bất ổn với cơ thể hãy đi khám và nhận lời tư vấn của bác sĩ.<br/>',
    '-The Moon không đem đến tin vui về tiền bạc. Những nguồn tiền của bạn sẽ tạm thời chảy rất chậm trong giai đoạn này. Một chế độ chi tiêu “thắt lưng buộc bụng” trong giai đoạn này là điều cần thiết. Không nên phụ thuộc hoặc dồn hết tâm trí vào một nguồn tiền cố định, hãy nghĩ cách xoay xở tài chính bằng chính năng lực của bản thân.<br/>-The Moon mang đến thông điệp rằng ngoài bạn ra không ai có thể kéo bạn ra khỏi vũng lầy của khủng hoảng tài chính được. Lá bài cũng cảnh báo có sự xuất hiện của sự dối trá và lừa lọc liên quan đến tiền bạc.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/19-The-Sun.jpg',
    '-Người như The Sun tỏa sáng như ánh Mặt Trời vậy. Họ có sức hút mạnh mẽ với mọi người.<br/>-The Sun như đứa trẻ, mang tới niềm vui, sự ấm áp, thuần khiết nhưng cũng khá vô tâm. Đôi khi năng lượng của họ hướng ra ngoài nhiều tới mức họ chẳng quan tâm tới tình yêu. Nhưng khi bị thu hút bởi ai đó, họ vô cũng nhiệt thành. Và đối phương cũng bị cuốn hút vào họ.<br/>-Nhưng tình yêu không đơn giản là sự cuốn hút. Nếu muốn đi xa với nhau, khả năng thấu hiểu chính là cái mọi mối quan hệ cần có.<br/>-Khi đang trong một mối quan hệ lâu dài, thì The Sun là dấu hiệu vô cùng tích cực. Nó là lá bài của niềm vui, hạnh phúc. Nó chỉ ra tình trạng mối quan hệ của bạn : tỏa sáng, hạnh phúc và bền vững.<br/>',
    '-Hình ảnh tươi sáng mang tới ý nghĩa tích cực. Khi gặp The Sun đồng nghĩa công việc của bạn đang hoặc sắp tới thời điểm thuận lợi. Bạn cần bám sát con đường và sự lựa chọn của mình, không ngừng nỗ lực. Đơn giản hóa và rõ ràng mọi thứ trong kế hoạch của mình. Điều đó khiến thành công của bạn càng sớm và càng rực rỡ hơn.<br/>-Theo quy luật cân bằng, sau những khó khăn tình trạng của bạn đang tốt đẹp lên rất nhiều khi gặp The Sun. Chân lý luôn có sự hấp dẫn tự thân. Bạn chỉ cần kiên trì thúc đẩy ý tưởng của mình, bạn sẽ không thất bại. <br/>-The Sun còn là lá bài về sự chủ động trí tuệ và hành động. Đã đến thời điểm bạn nhân được về những thành quả của mình. Tính tích cực rõ rệt biểu thị cho sự thành công trong công việc cũng như tiền bạc.<br/>',
    '-The Sun đại diện cho ánh mặt trời mang đến những điều may mắn đối với tình trạng sức khỏe của bạn.<br/>-Giai đoạn này bạn luôn căng tràn năng lượng cùng sự nhiệt huyết, dành nhiều thời gian cho hoạt động ngoại khóa hoặc những chuyến dã ngoại ngắn ngày mang đến một tinh thần lạc quan.<br/>-Nếu bạn đang trong quá trình chữa bệnh thì The Sun dự báo tình hình sẽ sớm chuyển biến tốt. Hãy duy trì thể lực cùng tinh thần hiện tại để đủ năng lượng thực hiện mọi ước muốn của bản thân.<br/>',
    '-Tiền bạc trong thời gian này khá dồi dào, bạn sẽ nhận được nhiều khoản tài chính từ nhiều nguồn khác nhau. Lá bài The Sun mang đến những thông báo tích cực về mặt tài chính. <br/>-Tuy nhiên, bạn cần hết sức cảnh giác về sự chi tiêu của mình, nhiều tiền đồng nghĩa với việc nhiều khoản phải chi trả. Hãy cân đối chi tiêu, tốt hơn hết là bạn hãy đầu tư cho những dự án kinh doanh để thu được lợi nhuận và hạn chế chi tiêu phung phí.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/20-Judgement.jpg',
    '-Nếu bạn vẫn còn đang do dự không muốn yêu, Judgement chỉ ra rằng bạn thiếu tự tin.<br/>-Bạn luôn tự đánh giá và khắt khe với bản thân. Sự khắt khe ấy không phù hợp với tình yêu. Bạn cần thoải mái hơn và lắng nghe cảm xúc của mình. Sự đánh giá, suy xét sẽ khiến người bạn để ý hay người để ý bạn bị tổn thương. Điều này sẽ đẩy họ xa bạn.<br/>-Và nếu đang trong một mối quan hệ lâu dài, Judgement yêu cầu bạn nhìn nhận lại bản thân. Có thể vô tình hoặc cố ý bạn đã làm cho đối phương bị tổn thương. Nhưng bạn lại không nhận thức được điều đó, và nó ảnh hưởng đến tình yêu của bạn.<br/>-Judgement muốn bạn cân nhắc trước khi hành động và dám chịu trách nhiệm nếu muốn đi xa với nhau.<br/>',
    '-Judgement xuất hiện bạn sẽ có hai vấn đề cần lưu tâm. Một là kết quả mà những hoạch định lúc trước của bạn mang lại và bạn không thể né tránh. Hai là con đường tiếp theo bạn chuẩn bị đi và bạn cần chuẩn bị cho điều này.<br/>-Với chủ đề về sự phán xét và quyết định cuối cùng Judgement nhấn mạnh vào tầm nhìn xa của bạn. Khi đưa ra những quyết định cuối cùng, tạo nền tảng cho hướng đi kế tiếp.<br/>-Bạn cần chú ý vấn đề đàm phán và những mối quan hệ. Có thế nó sẽ có ảnh hưởng tới tài chính của bạn ở hiện tại và cả tương lai. Do đó bạn cần sáng suốt loại bỏ những yếu tố cũ không cần thiết.<br/>-Cũng như bạn cần duy trì những mối quan hệ có lợi trong công việc. Judgement yêu cầu sự quyết đoán, khôn ngoan và chu toàn khi đưa ra quyết định cuối cùng.<br/>',
    '-Trường hợp bạn đang có vấn đề về sức khỏe thì The World  dự báo tình hình sẽ tốt lên trong thời gian tới. Việc cần làm là thả lỏng và tận hưởng thời gian nghỉ ngơi.<br/>-Mặt tiêu cực, The World  dự báo những căn bệnh đã phát sinh từ lâu tại cơ thể bạn đang phát triển theo chiều hướng xấu, nên đi kiểm tra và kịp thời điều trị nếu có vấn đề. <br/>-The World ám chỉ sự chuyển tiếp và thay đổi, sức khỏe của bạn cũng có sự xoay chuyển nên việc quan tâm tới tất cả các dấu hiệu lạ giúp bạn phòng ngừa được bệnh tật trước khi chúng đi quá xa.<br/>',
    '-Judgement mang đến những tín hiệu tốt về tình hình tài chính. Bạn sẽ thu lại những khoản tiền lớn sau những đầu tư mạo hiểm.<br/>- Nếu bạn đang chờ những nguồn tiền từ các khoản thu nhập cá nhân thì rất nhanh thôi, chúng sẽ về tay bạn. Nhiều khoản tiền sẽ đến nhưng đồng nghĩa với việc nguồn gốc của chúng phải được xác định rõ ràng.<br/>-Lá bài Judgement cảnh báo những nguồn tiền không rõ ràng, phi pháp có thể khiến bạn xuống dốc và sụp đổ nhanh chóng .',  ),
  createCardDatas(
    '../img/TarotCard/21-The-World.jpg',
    '-The World xuất hiện khi bạn chưa có mối quan hệ nào, có thể đó là do bạn vẫn còn buồn về chuyện cũ. Chuyện tình cảm khiến bạn bị tổn thương và không dám tiến đến mối quan hệ tình cảm nào mới.<br/>-Nhưng khi bạn dành tình cảm cho ai đó, The World sẽ là lời chắc chắn về chuyện tình cảm của đối phương cũng dành cho bạn.Trong tương lai đây sẽ là một mối quan hệ rất có triển vọng, tình cảm của hai người sẽ rất sâu sắc.<br/>-Và khi đang trong một mối quan hệ lâu dài, The World có thể biểu thị sự cân bằng, hòa hợp về tình cảm của hai bạn. Khi lá bài xuất hiện bạn có thể mong chờ vào tương lai của mối quan hệ. Một mối quan hệ chính thức được công nhận với tất cả mọi người.<br/>',
    '-The World đưa ra lời tiên đoán về vật chất, tổng thể hòa hợp. Bạn cần có sự bình thản và kiên trì trong kế hoạch của mình. Lúc này dường như không có sự thúc ép nào nên bạn có thể thong thả tự tin vận hành công việc của mình.<br/>-Với lời tiên đoán về đạt được thành tựu nào đó qua một cuộc hành trình của The World. Bạn cần giữ tinh thần tích cực để vận dụng những kĩ năng của mình để mang lại lợi ích cho bản thân và công việc. <br/>-Và lá bài còn tiên đoán về việc bạn sẽ đạt được thành công, bội thu về tiền bạc, kinh nghiệm. Bạn cần duy trì được công việc và cách thức đầu tư, sử dụng tiền bạc của mình. Nhưng cũng cần lưu ý duy trì mối quan hệ trong công việc, hãy giữ hòa khí.<br/>',
    '-Trường hợp bạn đang có vấn đề về sức khỏe thì The World  dự báo tình hình sẽ tốt lên trong thời gian tới. Việc cần làm là thả lỏng và tận hưởng thời gian nghỉ ngơi.<br/>-Mặt tiêu cực, The World  dự báo những căn bệnh đã phát sinh từ lâu tại cơ thể bạn đang phát triển theo chiều hướng xấu, nên đi kiểm tra và kịp thời điều trị nếu có vấn đề. <br/>-The World ám chỉ sự chuyển tiếp và thay đổi, sức khỏe của bạn cũng có sự xoay chuyển nên việc quan tâm tới tất cả các dấu hiệu lạ giúp bạn phòng ngừa được bệnh tật trước khi chúng đi quá xa.<br/>',
    '-Những vấn đề về tài chính trước đó khiến bạn lâm vào trạng thái đói kém. Đừng lo lắng vì The World thông báo giai đoạn này sẽ nhanh qua đi.<br/>-Bên cạnh đó, bạn nên quản lý lại tình hình tài chính và bắt đầu có kế hoạch tiết kiệm vì The World cảnh báo sẽ có những bất lợi trong thời gian tới cần dùng đến tiền.<br/>-Nếu bạn đang quá eo hẹp về kinh tế và muốn vay vốn thì người thân sẽ là nguồn tiền an toàn, tránh vay mượn từ những người xã giao. Ngược lại, nếu bạn có ý định cho vay thì nên cân nhắc vì việc thu hồi lại tương đối mất thời gian.<br/>',
  ),
   createCardDatas(
    '../img/TarotCard/22-Ace-of-Wands.jpg',
    '-Trong tình yêu Ace Of Wands đại diện cho những ham muốn nguyên thủy về tình dục và sự thống trị. <br/>-Mối quan hệ mà bạn đang nghĩ tới chưa hẳn  là tình yêu.<br/>-Nếu bạn bỗng nhiên chú ý tới một người. Ace Of Wands cho rằng giữa hai bạn có một sự thu hút khó có thể che giấu. <br/>-Ace Of Wands cho thấy hai bạn có khả năng sẽ chấp nhận nhau. Nhưng mối quan hệ đó kéo dài bao lâu thì chưa thể biết được. <br/>-Bởi tình yêu ngoài những thời gian mãnh liệt còn có những giây phút sóng gió, thử thách mà chưa chắc ai cũng có thể vượt qua.<br/>-Ace Of Wands có sức sống mạnh mẽ và năng lượng của đam mê. Nếu nó xuất hiện nghĩa là cuộc sống của bạn đang ngập tràn sự hào hứng.<br/>',
    '-Ace Of Wands là lá bài khởi đầu của hệ gậy. Nó thể hiện về mặt tư tưởng trong việc hoạch định các vấn đề của bạn.<br/>-Sự khởi đầu của công việc trong lời tiên thể hiện hình ảnh bước đi đầu tiên trên con đường công danh.<br/>-Bạn nên tập trung vào hoạch định những bước đầu tiên cho công việc, tránh việc hăng hái mà đi quá xa vì dù sao đây mới chỉ là bước khởi đầu.<br/>-Bạn cần phải chứng tỏ với người khác năng lực của mình, cũng như rõ ràng tạo ra sự yên tâm cho người hợp tác.</br>-Cần thể hiện được tính tích cực trong suy nghĩ của mình tới mọi người xung quanh. </br>-Bạn cần phát huy tinh thần, năng lực của mình đúng lúc, tránh để bản thân bị cuốn hút bằng những thứ không quan trọng hoặc mâu thuẫn. </br>-Cần giữ sự tập trung vào công việc và những khó khăn trước mắt. </br>-Ace Of Wands khuyên bạn sử dụng tinh thần và nhiệt huyết cũng như sự chân thành để giao tiếp với đồng nghiệp khi bắt đầu công việc. </br>',
    '-Ace of Wands ám chỉ những bệnh tật di truyền từ nhiều thế hệ trong dòng họ. Bạn có thể mắc một căn bệnh di truyền từ ông bà, bố mẹ<br/-Hết sức cẩn trọng khi cơ thể có dấu hiệu lạ, những cơn dịch cúm hoặc sốt từ người thân cũng có thể lây lan nếu bạn không phòng tránh đúng cách.<br/>-Điều may mắn là tuy bệnh di truyền nhưng Ace of Wands dự báo đây không phải căn bệnh nặng, chịu khó kiêng kỵ và ăn uống điều độ bạn sẽ khỏe lại.',
    '-Ace of Wands thông báo rằng bạn có thể nhận được một khoản tiền lớn trong thời gian tới. Đó có thể là tiền thưởng cho những ý tưởng sáng tạo thông minh của bạn, bạn gần như thỏa mãn và tận hưởng thành quả của mình<br/>-Mặt khác, lá bài cho rằng số tiền bạn nhận được có thể từ một khoản thừa kế, hoặc khoản tiêu vặt lớn từ gia đình<br/>-Nhìn chung, tình hình tài chính trong thời gian tới tương đối dồi dào. Nhớ tiêu tiền đúng cách và cám ơn những người đã trao số tiền đó cho bạn.',
  ),
  createCardDatas(
    '../img/TarotCard/23-Two-of-Wands.jpg',
    '-Two Of Wands là một lá bài thuận lợi.<br/>-Nó ám chỉ một số thay đổi sắp đến trong cuộc sống của bạn và bạn sẵn sàng trong trạng thái tuyệt vời để đón nhận. <br/>-Bạn rất cố gắng trong việc hoàn thiện bản thân. Và đây là thời điểm Two Of Wands để bạn thấy được kết quả từ nỗ lực của mình. Một mối quan hệ mới sẽ nhanh chóng đến với bạn. <br/>-Tuy vậy, về sau bạn lại cảm thấy nghi ngờ về tính định hướng của mỗi quan hệ. <br/>-Trong thời gian này, Two Of Wands khuyên bạn nên xem xét kỹ lại. Những sự lựa chọn cũng như tính định hướng của cả hai trước khi bước vào mối quan hệ. <br/>-Two Of Wands là dấu hiệu của những thay đổi mới trong tình yêu của bạn. Tuy nhiên nó không hề tiêu cực.<br/> -Trong một số trường hợp, Two Of Wands còn cho thấy bạn cần đưa ra quyết định. Cũng như bạn phải tin tưởng vào định hướng của bản thân.<br/>',
    '-Two Of Wands là lá bài thứ hai trong các lá ẩn phụ bộ Gậy. Thể hiện trạng thái tiếp thu, đang vận dụng các tri thức trong việc hoạch định các kế hoạch công việc của. <br/>-Two Of Wands khuyên bạn cần tập trung học hỏi cho tốt trước khi thiết lập kế hoạch. Vì điều đó sẽ tiết kiệm được nhiều thời gian và công sức. <br/>-Nếu đang trong giai đoạn đàm phán, bạn cần kiểm soát tốt các ý tưởng của mình. <br/>-Two Of Wands hướng tới việc tiếp tục phát huy những yếu tố tích cực đã được mở đầu từ trước. Đồng thời với việc tiếp tục mở rộng sức ảnh hưởng của hoạch định ban đầu. Bạn còn phải có sự tính toán trước các bước đi tiếp theo. Để duy trì, giữ gìn sự phát triển và ổn định về thu nhập tài chính. <br/>-Đối với những mối quan hệ đang có, cần tiếp tục phát triển để có được sự ủng hộ.<br/>',
    '-Lá bài Two of Wands dự báo sự nghiệp ở đỉnh cao, tiền bạc không phải lo nghĩ chính là giai đoạn bạn phải chăm lo kỹ lưỡng cho sức khỏe. <br/>-Mọi lo âu, phiền muộn có thể diễn ra trong giai đoạn này, những vấn đề về sức khỏe đang diễn ra theo chiều hướng xấu. <br/>-Điều cần làm nhất là sinh hoạt theo một chế độ lành mạnh và khám sức khỏe định kỳ đều đặn. <br/>-Trường hợp bạn đang nhận điều trị thì phương thuốc tốt nhất là tinh thần, sự an ủi động viên từ phía gia đình sẽ giúp bạn khá hơn rất nhiều.',
    '-Đi cùng sự thành công của sự nghiệp, tiền bạc trong giai đoạn này khá dồi dào. Bạn sẽ có cuộc sống dư dả và thoải mái, kế hoạch đầu tư cho kinh doanh hoặc vay mượn trở nên dễ dàng hơn. <br/>-Lời khuyên của lá bài Two of Wands là bạn nên đầu tư cho sở thích cá nhân, tận hưởng khoảng thời gian thảnh thơi trước khi mọi thứ bận rộn trở lại. <br/>-Thật may mắn khi không có bất kỳ một vấn đề nào về tiền bạc nào phát sinh trong lá bài này.',
  ),
  createCardDatas(
    '../img/TarotCard/24-Three-of-Wands.jpg',
    '-Three Of Wands phản ánh một giai đoạn của sự nghỉ ngơi. Đây không phải là thời điểm tốt để yêu đương. Tâm trạng của bạn đang đầy mâu thuẫn. <br/> -Nếu đã cảm thấy khó điều chỉnh cảm xúc, Three Of Wands khuyên bạn hãy thực hiện một chuyến đi xa. Nó sẽ mang lại cho bạn những trải nghiệm sâu sắc hơn về bản thân mình. Và bạn sẽ nhận ra mình mong muốn gì câu chuyện tình cảm. <br/>-Khi bạn đang để ý tối một người, Three Of Wands phản ánh sự thiếu quan tâm của bạn. Đối phương nghĩ rằng bạn khá hờ hững. Tuy rằng cảm xúc là thật nhưng bạn lại không biết cách thể hiện ra đến ngoài. Bạn cần phải rõ ràng hơn. Hãy bộc lộ tình cảm một cách thoải mái cũng như nói rõ về tình cảm của mình. <br/>-Nếu muốn tiến lên một một quan hệ lâu dài. Three Of Wands khuyên bạn cần dành thời gian quan tâm chăm sóc, hiểu thêm về đối phương. Trong một mối quan hệ lâu dài bạn cần xác định rõ và định hướng mối quan hệ. Và bạn cần thẳng thắn bày tỏ tình cảm cũng như định hướng của mình để đối phương hiểu rõ về bạn. <br/>-Đôi khi Three Of Wands phản ánh sự nghi hoặc của bạn về mối quan hệ. Vì quá háo hức mong chờ mà bạn nhanh chóng bước vào một mối quan hệ. Bạn nhận ra rằng mình vẫn chưa thể quen với việc phải chăm sóc lo lắng cho người khác. Bạn cần phải thả lỏng bản thân và yêu quý hiện tại của mình. <br/>',
    '-Three Of Wands tương ứng với sự bảo hộ trong tiến hành công việc. Điều này chứng tỏ các ý tưởng và phương án của bạn đang được đồng tình và ủng hộ. <br/>-Sức mạnh ổn định và quyết định đúng đắn thể hiện trạng thái của bạn. Có vẻ bạn đã sử dụng tốt những kỹ năng học được từ các giai đoạn trước. Three Of Wands đưa ra lời khuyên là cần tiếp tục nỗ lực. Dựa trên những thành quả và nền tảng trước đó. <br/>-Three Of Wands nói về một người đứng đầu dẫn dắt và có tầm nhìn. Những phẩm chất mà bạn có được chính là một yếu tố quan trọng. Đó là điều giúp bạn có thể đàm phán vào việc thúc đẩy công việc tiến lên. <br/>-Three Of Wands yêu cầu bạn cần có tầm nhìn xa. Vì ở vai trò quan trọng thì không thể đưa ra những quyết định ngắn hạn và vì lợi ích cá nhân. Nếu bạn đang được đầu tư cần tận dụng tốt những giúp đỡ tài chính mà mình đang có. Nó sẽ tạo ra những nguồn thu nhập tài chính ổn định và lâu dài cho bạn. <br/>-Và khi bạn có một vị trí tốt trong công việc thì cần phải giữ vững được vị trí hiện tại của mình. Cố gắng tận dụng mọi cơ hội để đưa công việc tiến lên. Thêm vào đó Three Of Wands cũng nhắc bạn cần tận dụng những sự giúp đỡ, mối quan hệ. Nó sẽ giúp cho dự định của bạn trở nên hoàn thiện hơn. <br/>',
    '-Three of Wands nói rằng sự lao động quá sức sẽ khiến bạn kiệt sức. Cân bằng sức khỏe là điều quan trọng phải thực hiện, không nên để cơ thể hoạt động liên tục cũng không nên ì ạch không vận động gì. <br/>-Những bài tập nhẹ, đi bộ thường xuyên rất tốt. Bạn nên thực hiện lối sống lành mạnh, ăn nhiều rau củ, đồ mát, ngủ nghỉ điều độ để tránh các căn bệnh do căng thẳng gây ra. <br/>-Ngoài ra, Three of Wands cảnh báo một số vấn đề về tình dục có thể gây ảnh hưởng xấu tới sức khỏe. <br/>',
    '-Những chuyến xả hơi, nghỉ mát là cần thiết để thư giãn nhưng bạn không nên phung phí quá nhiều ngân sách để phục vụ sở thích cá nhân. <br/>-Lá bài Three of Wands cảnh báo bạn nên tiết kiệm tiền để chuẩn bị cho tương lai. <br/>-Trong thời điểm sắp tới sẽ có những cơ hội nghề nghiệp tìm đến, việc chuẩn bị tài chính từ trước sẽ giúp bạn thuận lợi trong việc đầu tư và gọi vốn. <br/>',
  ),
]

const createOptionDatas = (name, img, color, link) => {
  return { name, img, color, link };
};

export const optionDatas = [
  createOptionDatas('Tình cảm', './img/icon/loveIcon.png', 'bg-tarot-pink', '/detail/love'),
  createOptionDatas('Sự nghiệp', './img/icon/careerIcon.png', 'bg-tarot-blue', '/detail/career'),
  createOptionDatas('Sức khỏe', './img/icon/healthIcon.png', 'bg-tarot-green', '/detail/health'),
  createOptionDatas('Tiền bạc', './img/icon/moneyIcon.png', 'bg-tarot-yellow', '/detail/money'),
]