const createCardDatas = (img, love, career, health, money) => {
  return { img, love, career, health, money };
};

export const cardDetailDatas = [
  createCardDatas(
    '../img/TarotCard/0-The-Fool-Male.png',
    '-Nếu ở giai đoạn tìm hiểu. The Fool cứ ngỡ tình yêu là thế giới toàn màu hồng, không vội vã yêu mà bắt đầu mơ mộng về nửa kia của mình.<br/>-The Fool dường như hết mức ngây ngô đối với tình yêu. Trong chuyện tình cảm, ngay khi nửa kia thể hiện sự quan tâm lập tức họ vui sướng phát điên. Thật may mắn cho ai đó yêu được The Fool. Niềm đam mê thuần khiết, sự ngây thơ, chân thành không tính toán của họ là một món quà.<br/>-Mặc dù ở bên họ là một trải nghiệm thú vị. Nhưng khi ở trong một mối quan hệ lâu dài đôi khi sẽ trở thành một sự phiền phức.<br/>- Nếu muốn nâng tầm mối quan hệ, The Fool cần trang bị cho mình thêm thật nhiều kiến thức và kĩ năng về cuộc sống cho một hành trình dài hơi.<br/>',
    '-The Fool thể hiện một sự khởi đầu. Đề ra ý tưởng cũng như tính toán trong công việc. Giai đoạn này vẫn trong trạng thái hình thành tư tưởng. Xây dựng kế hoạch cho bản thân và vẽ ra viễn cảnh trong tương lai về 1 công việc đầy mơ ước. Nhìn chung viễn cảnh được vẽ ra một cách khá tích cực và ẩn chứa rất nhiều năng lượng nhiệt huyết, đam mê. Dám dấn thân nên mọi thứ bước đầu sẽ có tính khả quan. <br/>-Nhưng nhược điểm của The Fool là thiếu kinh nghiệm cũng như kĩ năng cần thiết. Vì vậy, cần phải nỗ lực cân bằng ý chí và khả năng để có thể có được quyết định đúng đắn nhất.<br/>-Đôi khi sự liều lĩnh, không cân nhắc kĩ sẽ dẫn tới tổn thất về mặt tài chính. Cần cẩn trọng trong việc chi tiêu, tránh việc quá mạo hiểm và liều lĩnh để hạn chế những rủi ro có thể.<br/>',
    '-Lá bài thể hiện sự lơ là của bạn trong việc chăm sóc bản thân. Sự hậu đậu và chủ quan sẽ khiến sức khỏe của bạn gặp nhiều biến động xấu. Lá bài ám chỉ sự suy sụp về sức khỏe và tinh thần có thể liên quan tới rượu hoặc chất kích thích. Bạn nên điều chỉnh lại thói quen sinh hoạt và kiềm chế bản thân trước các trò vui vô bổ, không bến bờ.<br/>',
    '-Lá bài thể hiện sự hoang phí đang diễn ra trong chi tiêu của bạn. Sự đầu tư hoặc chi trả cho các vấn đề của bạn đang thiếu sự chừng mực, sự đầu tư đó có thể là phục vụ cho đam mê của bạn nhưng nó đang ở mức độ phung phí cần điều chỉnh. Lá bài ám chỉ bạn nên xem xét lại kế hoạch chi tiêu của mình sao cho hợp lý.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/1-The-Magician.png',
    '-The Magician là một đối tượng hoàn hảo trong tình yêu. Họ hiểu rõ khả năng của mình và thực hiện một cách nhuần nhuyễn.<br/>-Phép thuật của The Magician sẽ mang 2 bạn lại gần nhau. Đó là sự hấp dẫn lẫn nhau, thấu hiểu vả thông cảm. The Magician còn báo hiệu rằng bạn hoàn toàn mê đắm đối phương.<br/>-Điểm cần khắc phục là The Magician có một cái tôi khá cao. Đôi khi chuyện tình cảm không phải là câu chuyện thắng thua. Nhưng là một người khôn khéo, mọi việc đều nằm trong tầm kiểm soát của Pháp Sư.<br/>',
    '-The Magician đại diện cho nhân vật đang học hỏi, tiếp nhận và vận dụng kĩ năng cần thiết cho công việc của mình.<br/>-Pháp Sư có sự khôn khéo, giỏi thích ứng đối với mọi khía cạnh trong công việc của mình. Có vẻ sự khôn khéo này sẽ giúp cho The Magician nhận được nhiều nguồn lực hỗ trợ về công việc cũng như công việc.<br/>-Lá bài nhấn mạnh việc cần trang bị cho mình kĩ năng khi muốn đạt được mục tiêu cũng như thăng tiến trong công việc.<br/>',
    '-Lá bài cho biết mọi sự quyết tâm của bạn sẽ mang đến áp lực không nhỏ. Bạn sẽ rơi vào tình trạng lo lắng, bệnh tật có thể đến bạn nên có sự chuẩn bị. Sự chuẩn bị tâm lý và sức khỏe ngay từ lúc ban đầu sẽ giúp bạn dễ dàng ứng phó với những khó khăn. Thể lực có thể bị ảnh hưởng, căng thẳng có thể dẫn đến những trận ốm dai dẳng.<br/>-Nên chú ý tới các gói bảo hiểm để đề phòng trường hợp xấu xảy ra. The Magician đưa ra lời khuyên bạn nên chăm chỉ tập luyện, giữ tâm lý vui vẻ, lắng nghe tiếng nói của bản thân để đẩy lùi bệnh tật.<br/>',
    '-The Magician cho thấy dấu hiệu của sự sung túc và giàu có. Bạn sẽ không phải lo ngại về các vấn đề tài chính, các nguồn thu sẽ dồi dào. Tuy nhiên, lá bài cũng cho thấy bạn sẽ bị mất mát nếu vay mượn. Rất nhiều phi vụ làm ăn với lợi nhuận hấp dẫn sẽ đến, hết sức cẩn thận và tỉnh táo để không quyết định sai lầm. Nguồn tài chính cá nhân sẽ tăng lên nhưng nguy cơ của sự mất mát cũng tăng, nên bảo quản tốt tiền bạc để tránh thất thiệt.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/2-The-High-Priestess.png',
    '-The High Priestess ám chỉ một người nội tâm và nhạy cảm.<br/>-Mặc dù vậy họ không hề yếu đuối, Nàng biết cách điều khiển cảm xúc và kiến thức của bản thân. Nếu bạn đang định bắt đầu một mối quan hệ mới , The High Priestess đề cao trực giác của bạn.<br/>-Hãy đánh giá lại người bạn quan tâm. Bạn cần cảm nhận đối phương bằng nội tâm.<br/>-The High Priestess đại diện cho sự khôn ngoan và cả sự thanh thản. Sâu trong tiềm thức nàng sẽ tìm ra vấn đề và giải quyết đúng lúc.<br/>',
    '-The High Priestess là sự đào sâu về mặt chuyên môn. Lời khuyên của lá bài này là hoạch định kế hoạch tốt. Chau dồi khả năng chuyên môn, học hỏi phải có sự chọn lọc các yếu tố tốt xấu để đối phó những công việc xảy ra sau này. <br/>-ương ứng về vấn đề tài chính, The High Priestess thể hiện sự học hỏi về việc sử dụng những nguồn lực tài chính hiệu quả nhất.<br/>-The High Priestess còn nhắc nhở rằng cân nhắc trước khi đưa ra quyết định. Trong giai đoạn ẩn chứa những nguy hiểm tiềm tàng, cần nâng cao bản lĩnh và kiến thức để vượt qua trở ngại. The High Priestess còn thể hiện sự tiếp thu tri thức từ những bậc tiền bối<br/>',
    '-Lá bài với hình ảnh nữ tu huyền bí nhắc nhở bạn nên chăm sóc những người phụ nữ trong gia đình và chính bản thân mình nếu bạn là nữ giới.<br/>-Sự che giấu của lá bài báo hiệu những hiểm họa về sức khỏe có thể xảy đến, quan tâm chăm sóc sức khỏe của chính bạn và người thân là việc cấp thiết ngay lúc này.<br>',
    '-Lá bài đại diện cho sự chắc chắn trong chi tiêu. Các khoản tài chính của bạn đang dần ổn định, kế hoạch thắt chặt chi tiêu đang có những hiệu quả tốt. Đây cũng là lúc các khoản vay mượn của bạn trở nên dễ dàng.<br/>-Tuy nhiên, sự chủ quan sẽ gây ra hậu quả đáng tiếc. Mọi hoạt động vay mượn, ký kết của bạn nên có giấy tờ chứng thực rõ ràng dựa vào sự thỏa thuận giữa hai bên.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/3-The-Empress.png',
    '-The Empress là hình ảnh người mẹ. Đó là một người phụ nữ lí tưởng trong gia đình, không phải trong tình yêu. Sự ân cần, quan tâm chăm sóc và chăm sóc mọi thứ chỉn chu giúp bạn ghi điểm trong mắt mọi người.<br/>-Nhưng đôi khi sự hoàn hảo của bạn là áp lực rất lớn với đối phương. Và đối với những đối tượng chua đủ chín chắn, hiểu được giá trị, họ sẽ không nhìn ra sự tuyệt vời của bạn.<br/>-Nhưng The Empress đại diện cho sư chung thủy. Đối với họ sẽ không có chuyện bắt cá hai tay, hay lừa dối. Đối với gia đình The Empress sẵn sàng hi sinh những lợi ích cá nhân để chăm lo gia đình.<br/>-Nhưng đôi khi họ phải chú ý tới bản thân và chiều chuộng mình để giữ được sự chú ý của đối phương lâu dài<br/>',
    '-với tính chất của The Empress ta nhận ra lá bài này thể hiện sự tích cực và an toàn trong công việc. Lá The Empress thể hiện sự gia tăng, phát triển khuyến khích bạn đưa ra kế hoạch nhằm tiếp tục phát triển. Một ý tưởng tốt, kế hoạch tốt sẽ thu lại được những kết quả tích cực.<br/>-Khi gặp The Empress tròn trải bài về công việc, cần nhanh chóng nắm bắt thời cơ này. Bạn nên tranh thủ tối đa những nguồn lực, sự ủng hộ để đạt được những ưu thế. Và bạn cần giữ vững những phẩm chất khiến mọi người tin tưởng để tiếp tục nhận được những sự hậu thuẫn.<br/>-Các lời tiên đoán về The Empress đều thể hiện trạng thái vui vẻ hợp tác với đồng nghiệp. Và công việc cũng như sự nghiệp của bạn sẽ có bước tiến triển tốt.<br/>',
    '-The Empress mang đến tín hiệu tốt về tình trạng sức khỏe của bạn. Nếu bạn đang bị bệnh và nhận điều trị thì thời điểm này bệnh tình sẽ có những khởi sắc, bạn sẽ sớm khỏe mạnh trở lại nếu chăm sóc kỹ lưỡng.<br/>-Nếu bạn thường xuyên mỏi mệt, bực dọc lời khuyên là bạn nên nghỉ ngơi, cho bản thân những khoảng không gian thư giãn riêng, tránh làm việc quá sức.<br/>-Đi du lịch hoặc tham gia các hoạt động ngoại khóa ngắn hạn rất có ích để cải thiện tâm trạng và thể lực.<br/>',
    '-Lá bái thông báo thời cơ thích hợp cho những phi vụ đầu tư. Đây là lúc bạn không nên đắn đo quá lâu trước các quyết định liên quan tới tiền bạc để tránh bỏ lỡ cơ hội. Bạn có thể thoải mái trong vấn đề đi vay mượn và cho vay mượn, The Empress mang ý nghĩa dự báo những khoản đầu tư sẽ sinh lời mạnh mẽ.<br/>-Tuy nhiên, lá bài mang đến sự cảnh báo về sự phung phí. Nếu bạn đang sở hữu một khoản tài chính lớn nhưng không có kế hoạch đầu tư và sử dụng hợp lý thì tình trạng tiêu pha phung phí sẽ xảy ra.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/4-The-Emperor.png',
    'The Emperor là người có quyền lực tối cao. Sự kiêu ngạo và tự tôn chính là điểm yếu của họ trong tình yêu. Dù có tình cảm với đối với đối phương, cách quan tâm của họ cũng rất độc đáo. Họ sẽ tìm cách gây ảnh hưởng đến đối phương nhưng không để lộ tình cảm của mình.<br/>-Nhưng The Emperor là người có tính ổn định và cẩn trọng. Nên trong một mối quan hệ đặc biệt quan trọng, họ sẽ thể hiện sự quan tâm một cách âm thầm, lặng lẽ. Và cũng vì cao ngạo nên họ không thể hiện một cách cuồng nhiệt thái quá. <br/>-Nhưng ta luôn có thể tin tưởng về tính chung thủy, ổn định của The Emperor. Họ luôn có chuẩn mực đạo đức cao và truyền thống. Đôi khi ta sẽ thấy lá bài xuất hiện với cương vị người Cha, họ sẽ ảnh hưởng tới mối quan hệ tình cảm của bạn.<br/>',
    '-Khi gặp The Emperor trong trải bài liên quan đến công việc sẽ là một dấu hiệu tích cực. Có vẻ bạn đã tính toán kĩ càng, những ý tưởng được thể hiện vững vàng, chắc chắn và định hình được kết quả. Nhưng bạn cần giữ được thái độ ôn hòa dù đã có tính toán kĩ lưỡng.<br/>-The Emperor còn biểu thị cho quyền hành, ưu thế lớn trong đàm phán. Bạn có thể giữ vững địa vị và ứng phó với những rắc rối phát sinh. Trong đàm phán bạn cần lắng nghe những ý kiến bổ ích để đảm bảo thắng lợi toàn diện.<br/>-The Emperor thường kiểm soát tốt những vấn đề về tài chính và có khả năng làm việc độc lập. Nhưng chính vì vậy lời khuyên ở đây là không nên tự mãn về thành quả cũng như bản thân. Và khi công việc gặp phải những khó khăn, cần phải giữ vững nỗ lực và mục tiêu của mình.<br/>',
    '-The Emperor mang đến cảnh báo về những dấu hiệu lạ trên cơ thể. Nếu bạn cảm thấy có gì bất thường nên đi kiểm tra ngay. Vì những tham vọng trong công việc bạn sẽ bị áp lực và mệt mỏi hãy tăng cường các hoạt động tốt cho sức khỏe như thể dục, gym, đi bộ và thiền. Sự cẩn trọng trong tính cách sẽ giúp bạn nhận ra sự quan trọng của sức khỏe.<br/>',
    '-Ý nghĩa của The Emperor mách bảo rằng nếu bạn không muốn bị mất tiền oan thì nên cẩn thận trước các mối kinh doanh, hợp đồng béo bở. Sự thận trọng cần được đặt lên trên tất cả, bạn nên tuân theo các nguyên tắc quen thuộc, tránh sáng tạo hoặc bạo dạn đi một con đường mới vì đây không phải thời điểm lý tưởng.',
  ),
  createCardDatas(
    '../img/TarotCard/5-The-Hierophant.png',
    '-The Hierophant là một người chuẩn mực, truyền thống. Trong tình yêu cũng vậy, tính truyền thống đối với bạn là những giá trị vô giá. Một mối quan hệ truyền thống, phù hợp với các chuẩn mực đạo đức xã hội luôn thu hút bạn.<br/>-Khi theo đuổi đối phương, bạn thường theo mô tuýp cổ điển. Bao gồm : tìm hiểu kĩ càng, xây dựng sự tin tưởng, quan tâm, hẹn hò, thỉnh thoẳng tặng quà. Tuy không quá dồn dập nhưng khiến đối phương không thể quên.<br/>-Trong tình yêu, The Hierophant biểu hiện đây là một tình yêu dựa trên giá trị và niềm tin chung. Sự xuất hiện của lá bài cho thấy sự hài hòa trong mối quan hệ. Cả hai cùng ý thức rõ ràng về trách nhiệm và cố gắng vun đắp tình cảm.<br/>',
    '-The Hierophant mô tả nhân vật nắm quyền lực về mặt tinh thần. Lá bài chỉ ra những yếu tố mới lạ và ở phạm vi rất rộng so với hiểu biết của bạn. Nếu muốn đưa ra được những hoạch định cụ thể, cần có lời khuyên của người giỏi hơn. Xây dựng nhưng mối quan hệ dựa trên sự hòa hợp về tư tưởng để đưa ra những phương án tốt nhất.<br/>-Lời khuyên của The Hierophant trong công việc là bạn cần tập trung học hỏi những kinh nghiệm. Và tích cực mở rộng mối quan hệ và bạn sẽ nhận ra người thầy của mình.<br/>-Trong đầu tư và kinh doanh, lá bài khuyên bạn nên chọn lựa đối tác cẩn thận trong vấn đề tài chính. Một mối quan hệ hòa hợp về mặt tinh thần sẽ là ưu tiên số một cho bạn thời điểm này.<br/>',
    '-The Hierophant thông báo rằng bạn không nên bỏ sót bất cứ dấu hiệu lạ nào từ cơ thể. Sự thách thức từ công việc có thể khiến bạn suy sụp cùng tâm lý bất an, những bài thể dục nhẹ, tâm sự cùng người lớn tuổi hơn sẽ giúp cải thiện tình hình. Nếu bạn đang bị bệnh thì những niềm tin vào tôn giáo, tín ngưỡng có thể tạo ra chuyển biến tốt.<br/>',
    '-Mọi sự đầu tư và tiêu pha lúc này không mang lại may mắn như bạn nghĩ. The Hierophant khuyên bạn nên chi tiêu theo thói quen cũ, nguyên tắc cần được đặt ra để duy trì sự ổn định. <br/>-Đây không phải thời điểm tốt để đầu tư và mua bán, mọi thứ liên quan đến tiền bạc cần được quản lý chặt chẽ. Các mối kinh doanh hấp dẫn có thể mời chào, bạn không nên mạo hiểm với những điều mới lạ.<br/>-Nếu muốn đầu tư, vay mượn nên xin ý kiến tư vấn của chuyên gia hoặc người có kinh nghiệm. Bạn có thể gặp bất chắc về tài chính nếu mạo hiểm làm mọi thứ một mình.<br>',
  ),
  createCardDatas(
    '../img/TarotCard/6-The-Lovers.png',
    '- Con người ta thường dẽ dàng ngộ nhận tình cảm. Yêu thích ai đó thì dễ nhưng có một tình yêu đích thực thì rất khó. Tình yêu của The Lover là một tình yêu thực sự, lâu dài và bền vững.<br/>-Vậy nên bạn không nên vội vàng mà hãy chậm rãi chờ đợi một người thích hợp. Và nếu gặp họ , bạn thực sự rất may mắn. Cả hai đều hướng về nhau với tình cảm chân thật nhất.<br/>-he Lover nói rằng cả hai đều bị thu hút về nhau một cách sâu sắc. Nhưng cả hai đều chậm rãi tìm hiểu để chắc chắn về tình cảm và thể hiện mình coi trọng đối phương. Dường như cả hai sẽ bước vào một mối quan hệ nghiêm túc.<br/>-The Lover là sự đồng điệu giữa hai tâm hồn, hài hòa ở cấp độ cao nhất. Đây là một tình yêu không vụ lợi toan tính và sẽ bền vững lâu dài.<br/>',
    '-lá bài thể hiện rất rõ chủ đề tình cảm. Hiển nhiên là khi yêu thì cuộc sống của chúng ta nhất định bị chi phối. Có thể dẫn tới sự thay đổi kế hoạch. Việc dựa hoàn toàn vào tình cảm, bỏ qua yếu tố khác là việc làm thừa nhiệt huyết nhưng thiếu khôn ngoan.<br/>-Cần có sự kiểm tra và điều chỉnh kế hoạch trước khi thực hiện. Sự quyến rũ, vẻ đẹp, tình yêu của The Lover khiến bạn bị cuốn hút vào tình yêu.<br/>-Đôi khi mục đích của bạn cũng có thay đổi nhằm hướng tới những mong muốn tình cảm. Cần giữ một tinh thần tỉnh táo trong chi tiêu liên quan đến vấn đề tình cảm. Tránh chi tiêu quá nhiều theo cảm hứng nhất thời. Và tình yêu cũng là trạng thái tích cực và là nguồn động lực phát triển tài chính.<br/>',
    '- The Lovers mang ý nghĩa rằng bạn đang có vấn đề về sức khỏe, hãy tìm đến bác sĩ để nhận được lời tư vấn. Bạn không nên tự ý đoán bệnh và uống thuốc theo ý muốn để tránh gặp vấn đề. Vì là lá bài về tình yêu và sự đam mê nên cảnh báo của The Lovers cũng liên quan đến tình ái. Hãy cẩn thận hết sức vì bạn có thể mắc một vài căn bệnh liên quan tới tình ái.<br/>',
    '- Bạn sẽ nhận được những món tiền từ người thân trong gia đình hoặc bạn bè chí cốt. Mọi nỗ lực của bạn đang được đền đáp xứng đáng bằng những thành công về vật chất.<br/>-Cảnh báo từ The Lovers là không nên cho người khác vay mượn tiền, đặc biệt là bạn thân vì sự mất lòng trong quan hệ của cả hai có thể xảy ra. Nếu bạn đang muốn xoay vốn để kinh doanh hoặc bắt đầu xây dựng một nền tảng công việ mới hãy tìm đến các mối các quan hệ thật sự tin cậy, họ sẽ dốc sức giúp đỡ bạn.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/7-Chariot.png',
    '- The Chariot mang bản tính thích chinh phục. Mục tiêu càng khó thì họ càng có hứng thú. Đôi khi tính hiếu thắng lại mang tính phá hoại trong tình yêu. Thật đáng tiếc khi thời nay hầu hết người trẻ tuổi luôn mang một tâm lí hiếu thắng như vậy.<br/>- Mang tâm lý chinh phục, The Chariot sẽ tận dụng mọi thế mạnh để được sự ưu ái của đối phương. Cách thức của họ rất đa dạng, nhưng đôi khi sự háo thắng chưa chắc đã là tình yêu. <br/>-Nhưng khi bước vào một mối quan hệ lâu dài, The Chariot biểu thị cho khả năng cân bằng. Họ có đủ nghị lực để duy trì mục tiêu. Họ biết cách thể hiện mong muốn và đáp ứng được nhu cầu của tình yêu.<br/>- Đôi khi The Chariot còn là dấu hiệu bạn đang bị kiểm soát bởi đối phương. Họ là người quan tâm chăm sóc đối phương cũng như gánh vác, chia sẻ. Tuy đôi lúc họ cứng rắn, khó thỏa hiệp nhưng chỉ là họ quan tâm bạn quá mức mà thôi.<br/>',
    '-The Chariot trong chủ đề công việc thể hiện sự điều hành, quản lí. Được dự đoán về tính chiến thắng, thành công. Bạn được mô tả đã vượt qua được nút thắt khó khăn và có những tính toán đúng đắn. Lời khuyên là cần có sự phối hợp tốt các kỹ năng của mình trong hoạch định kế hoạch. <br/>-The Chariot cũng mô tả bản lĩnh của nhân vật, đã có sự thăng tiến và nắm vững nguyên tắc.Cần cẩn trọng tối đa trước khi đầu tư tài chính vào một việc nào đó. Nên cân nhắc những phương án dự phòng cũng như sự phân bố tiền bạc.<br/>-The Chariot thể hiện một chuyển đổi quan trọng trong việc quản lí, kiểm soát các vấn đề vật chất, thực tế. Bên cạnh sự cứng rắn để duy trì sự ổn định thì bạn cần có sự mềm dẻo, linh hoạt. Và đó cũng là nghệ thuật quản lí nhằm giúp bạn dễ dàng loại bỏ những cản trở trong công việc.<br/>',
    '- The Chario khuyên bạn nên dành thời gian nhiều hơn cho bản thân và gia đình. Thiên nhiên trong lành sẽ giúp bạn khỏe mạnh hơn, các buổi Yoga hay thiền là ý kiến hay.<br/>-Lá bài còn cảnh báo bạn tránh xa các chất kích thích và thức khuya. Sức khỏe có thể suy yếu do thói quen sinh hoạt thiếu lành mạnh và thời gian làm việc thiếu khoa học.<br/>',
    '- Lá bài The Chariot là lá bài tốt về mặt tài chính, tuy nhiên bạn đang chi tiêu thiếu chừng mực. Nếu bạn cần vay mượn và xoay vốn để đầu tư kinh doanh thì đây là lúc khá thích hợp nhưng nếu bạn đang định cho vay thì nên xem xét. <br/>-Nên xem xét tình hình tài chính và khả năng hoàn tiền của người đi vay để đưa ra mức cho vay hợp lý, tránh rủi ro và rạn nứt tình cảm. Lá bài còn khuyên bạn nên dành thời gian cho những chuyến nghỉ dưỡng để tinh thần được thư giãn.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/8-Strength.png',
    '- Lá Strength trong tình yêu ngược hẳn với tên gọi. Họ là một người khá yếu đuối và nhẫn nại. Họ mong muốn có một tình yêu mà đối phương có thể để bạn dựa vào. Tuy nhiên sự rụt rè quá mức khi chưa bước vào một mối quan hệ sẽ đánh mất cơ hội của bạn. <br/>-Strength nói đến một người nhu hòa, tâm tính mềm mại, nhẫn nại, dịu dàng. Khi theo đuổi ai đó, họ sẽ từ từ chăm chút mà ngần ngại nói ra tình cảm của mình. Họ hy vọng đối phương sẽ nhận ra tình cảm của mình. Sự ân cần thể hiện tình cảm chân thật của bạn khiến đối phương cảm động.<br/>-Tuy nhiên sự nhẫn nại của bạn đôi khi quá mức. Trong tình yêu đôi khi hãy để làn sóng đam mê của bạn được nổi dậy. Nó sẽ tiếp thêm sức mạnh cho mối quan hệ của bạn tiến lên.<br/>',
    '- Với chủ đề sức mạnh Strength đưa ra lời tiên đoán về lòng can đảm. Bạn cần phải có sự dũng cảm trong việc đưa ra những hoạch định đối với những khó khăn. Cần tập trung những nguồn lực mình có vào kế hoạch, khó khăn trước mắt. Cân nhắc kĩ trước khi đưa ra quyết định cuối cùng và cần có dũng khí thực hiện nó. Càng gần tới thành công tính chất khó khăn của công việc càng thể hiện.<br/>-Strength có sức mạnh để đối đầu. Kiên trì đến cùng theo đuổi điều mình đã xác định, khẳng định con đường đúng đắn của mình. Khi tiến hành đầu tư, đừng chỉ nghĩ trực tiếp tới khoản tiền thu về.<br/>-Thay vào đó Strength đưa ra lời khuyên hành động vì đam mê. Nó sẽ dẫn đường cho thành công kéo theo nguồn lợi về tiền bạc một cách chân chính. Hãy phát huy sức mạnh của bản thân.<br/>',
    '- Sự bận rộn của công việc khiến bạn không có nhiều thời gian riêng tư để chăm sóc sức khỏe. Các chế độ ăn uống giảm đạm và chất béo sẽ giúp bạn thanh lọc cơ thể. <br/>-Tránh mọi sự căng thẳng không cần thiết, bạn nên đến phòng tập gym nhiều hơn để cơ thể dẻo dai, ít ốm vặt. Nếu bạn đang bị bệnh thì hãy kiên trì và tin tưởng vào bác sĩ, lá bài Strength báo hiệu bạn sẽ sớm bình phục.<br/>',
    '- Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br/>-Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br>- Tuy nhiên, bạn nên cẩn thận trước lời mời gọi hợp tác hấp dẫn. Mọi kiến nghị quá hoàn hảo từ phía đối tác có thể là cái bẫy lớn chờ bạn nhảy vào, sự tỉnh táo và quyết đoán sẽ giúp bạn thoát khỏi tình huống này nhưng sự cảnh giác chưa bao giờ là thừa thãi.<br/>',
  ),
  createCardDatas(
    '../img/TarotCard/9-The-Hermit.png',
    '- The Hermit tượng trưng cho một con người cô độc. Dường như họ chỉ muốn sống một cuộc đời độc thân, tránh xa những phức tạp của tình yêu, hôn nhân, gia đình. Họ thích sự tự do của mình, đối với họ tình yêu không quá quan trọng.<br/>-ho dù The Hermit động tâm với một người khác, họ cũng không thừa nhận. Tâm thế cao ngạo cũng là một trở ngại với họ. Theo đuổi một người tuýp như The Hermit tuyệt đối rất vất vả.<br/>.Khi trong một mối quan hệ, ta thấy sự xuất hiện của The Hermit là ta sẽ thấy một sự bế tắc. Nó nói đến một sự tạm ngưng chia sẻ của một mối quan hệ. Ngay cả khi trong một mối quan hệ lâu dài, họ cũng cần rất nhiều không gian riêng.<br/>.Đôi khi bạn sẽ tủi thân khi trong mối quan hệ với The Hermit. Họ khá vô tâm và thờ ơ, lạnh nhạt với đối phương<br/>',
    '- The Hermit tượng trưng cho chủ đề trí tuệ, khôn ngoan và thận trọng. Vì vậy, nếu bạn đang cân nhắc bắt đầu một dự án công việc thì lá bài sẽ dành cho bạn những lời khuyên. Không nên quá phô trương, cần phải đưa ra những hoạch định và hành động cẩn thận, kín đáo. Đôi khi sự phô trương sẽ thu hút nhiều sự chú ý, khó khăn cho công việc của bạn.<br/>=Chủ đề của The Hermit còn là về tiềm thức. Lời khuyên là bạn cần tập trung, giữ được sự ổn định trong tinh thần, tránh bị dao động. Để đạt tới bản lĩnh này không hề dễ dàng. Cần xác định được mục đích cao nhất mà mình muốn theo đuổi, tập trung nguồn lực tài chính. Kiên trì theo đuổi và không nản chí khi gặp phải một số khó khăn nhất thời.<br/>',
    '- Đây là thời gian bạn hay bị ốm do sự thay đổi của môi trường sống. Thời tiết nắng mưa đột ngột khiến bạn rơi vào những cơn ốm dai dẳng không dứt, hạn chế ra ngoài và che chắn cẩn thận nếu bắt buộc phải di chuyển để bảo vệ sức khỏe. Nếu bạn đang điều trị thì lá bài The Hermit nói rằng sự an ủi, động viên từ phía gia đình cùng những người bạn thân thiết sẽ giúp bạn vượt qua được thời gian khó khăn này.<br/>',
    '- Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br/>-Đây là lá bài trung bình nếu xét trên khía cạnh tiền bạc, điềm báo mà Strength mang tới có cả ý nghĩa tích cực và tiêu cực. Đầu tiên, đây là lúc thích hợp để chi tiền cho các hoạt động kinh doanh. Sự mạo hiểm và mạnh mẽ sẽ giúp bạn trúng mánh lớn nếu đầu tư kỹ lưỡng, không nên do dự quá lâu để mất cơ hội tốt.<br>- Tuy nhiên, bạn nên cẩn thận trước lời mời gọi hợp tác hấp dẫn. Mọi kiến nghị quá hoàn hảo từ phía đối tác có thể là cái bẫy lớn chờ bạn nhảy vào, sự tỉnh táo và quyết đoán sẽ giúp bạn thoát khỏi tình huống này nhưng sự cảnh giác chưa bao giờ là thừa thãi.<br/>',
  ),
   createCardDatas(
    '../img/TarotCard/22-Ace-of-Wands.jpg',
    '-Trong tình yêu Ace Of Wands đại diện cho những ham muốn nguyên thủy về tình dục và sự thống trị. <br/>-Mối quan hệ mà bạn đang nghĩ tới chưa hẳn  là tình yêu.<br/>-Nếu bạn bỗng nhiên chú ý tới một người. Ace Of Wands cho rằng giữa hai bạn có một sự thu hút khó có thể che giấu. <br/>-Ace Of Wands cho thấy hai bạn có khả năng sẽ chấp nhận nhau. Nhưng mối quan hệ đó kéo dài bao lâu thì chưa thể biết được. <br/>-Bởi tình yêu ngoài những thời gian mãnh liệt còn có những giây phút sóng gió, thử thách mà chưa chắc ai cũng có thể vượt qua.<br/>-Ace Of Wands có sức sống mạnh mẽ và năng lượng của đam mê. Nếu nó xuất hiện nghĩa là cuộc sống của bạn đang ngập tràn sự hào hứng.<br/>',
    '-Ace Of Wands là lá bài khởi đầu của hệ gậy. Nó thể hiện về mặt tư tưởng trong việc hoạch định các vấn đề của bạn.<br/>-Sự khởi đầu của công việc trong lời tiên thể hiện hình ảnh bước đi đầu tiên trên con đường công danh.<br/>-Bạn nên tập trung vào hoạch định những bước đầu tiên cho công việc, tránh việc hăng hái mà đi quá xa vì dù sao đây mới chỉ là bước khởi đầu.<br/>-Bạn cần phải chứng tỏ với người khác năng lực của mình, cũng như rõ ràng tạo ra sự yên tâm cho người hợp tác.</br>-Cần thể hiện được tính tích cực trong suy nghĩ của mình tới mọi người xung quanh. </br>-Bạn cần phát huy tinh thần, năng lực của mình đúng lúc, tránh để bản thân bị cuốn hút bằng những thứ không quan trọng hoặc mâu thuẫn. </br>-Cần giữ sự tập trung vào công việc và những khó khăn trước mắt. </br>-Ace Of Wands khuyên bạn sử dụng tinh thần và nhiệt huyết cũng như sự chân thành để giao tiếp với đồng nghiệp khi bắt đầu công việc. </br>',
    '-Ace of Wands ám chỉ những bệnh tật di truyền từ nhiều thế hệ trong dòng họ. Bạn có thể mắc một căn bệnh di truyền từ ông bà, bố mẹ<br/-Hết sức cẩn trọng khi cơ thể có dấu hiệu lạ, những cơn dịch cúm hoặc sốt từ người thân cũng có thể lây lan nếu bạn không phòng tránh đúng cách.<br/>-Điều may mắn là tuy bệnh di truyền nhưng Ace of Wands dự báo đây không phải căn bệnh nặng, chịu khó kiêng kỵ và ăn uống điều độ bạn sẽ khỏe lại.',
    '-Ace of Wands thông báo rằng bạn có thể nhận được một khoản tiền lớn trong thời gian tới. Đó có thể là tiền thưởng cho những ý tưởng sáng tạo thông minh của bạn, bạn gần như thỏa mãn và tận hưởng thành quả của mình<br/>-Mặt khác, lá bài cho rằng số tiền bạn nhận được có thể từ một khoản thừa kế, hoặc khoản tiêu vặt lớn từ gia đình<br/>-Nhìn chung, tình hình tài chính trong thời gian tới tương đối dồi dào. Nhớ tiêu tiền đúng cách và cám ơn những người đã trao số tiền đó cho bạn.',
  ),
  createCardDatas(
    '../img/TarotCard/23-Two-of-Wands.jpg',
    '-Two Of Wands là một lá bài thuận lợi.<br/>-Nó ám chỉ một số thay đổi sắp đến trong cuộc sống của bạn và bạn sẵn sàng trong trạng thái tuyệt vời để đón nhận. <br/>-Bạn rất cố gắng trong việc hoàn thiện bản thân. Và đây là thời điểm Two Of Wands để bạn thấy được kết quả từ nỗ lực của mình. Một mối quan hệ mới sẽ nhanh chóng đến với bạn. <br/>-Tuy vậy, về sau bạn lại cảm thấy nghi ngờ về tính định hướng của mỗi quan hệ. <br/>-Trong thời gian này, Two Of Wands khuyên bạn nên xem xét kỹ lại. Những sự lựa chọn cũng như tính định hướng của cả hai trước khi bước vào mối quan hệ. <br/>-Two Of Wands là dấu hiệu của những thay đổi mới trong tình yêu của bạn. Tuy nhiên nó không hề tiêu cực.<br/> -Trong một số trường hợp, Two Of Wands còn cho thấy bạn cần đưa ra quyết định. Cũng như bạn phải tin tưởng vào định hướng của bản thân.<br/>',
    '-Two Of Wands là lá bài thứ hai trong các lá ẩn phụ bộ Gậy. Thể hiện trạng thái tiếp thu, đang vận dụng các tri thức trong việc hoạch định các kế hoạch công việc của. <br/>-Two Of Wands khuyên bạn cần tập trung học hỏi cho tốt trước khi thiết lập kế hoạch. Vì điều đó sẽ tiết kiệm được nhiều thời gian và công sức. <br/>-Nếu đang trong giai đoạn đàm phán, bạn cần kiểm soát tốt các ý tưởng của mình. <br/>-Two Of Wands hướng tới việc tiếp tục phát huy những yếu tố tích cực đã được mở đầu từ trước. Đồng thời với việc tiếp tục mở rộng sức ảnh hưởng của hoạch định ban đầu. Bạn còn phải có sự tính toán trước các bước đi tiếp theo. Để duy trì, giữ gìn sự phát triển và ổn định về thu nhập tài chính. <br/>-Đối với những mối quan hệ đang có, cần tiếp tục phát triển để có được sự ủng hộ.<br/>',
    '-Lá bài Two of Wands dự báo sự nghiệp ở đỉnh cao, tiền bạc không phải lo nghĩ chính là giai đoạn bạn phải chăm lo kỹ lưỡng cho sức khỏe. <br/>-Mọi lo âu, phiền muộn có thể diễn ra trong giai đoạn này, những vấn đề về sức khỏe đang diễn ra theo chiều hướng xấu. <br/>-Điều cần làm nhất là sinh hoạt theo một chế độ lành mạnh và khám sức khỏe định kỳ đều đặn. <br/>-Trường hợp bạn đang nhận điều trị thì phương thuốc tốt nhất là tinh thần, sự an ủi động viên từ phía gia đình sẽ giúp bạn khá hơn rất nhiều.',
    '-Đi cùng sự thành công của sự nghiệp, tiền bạc trong giai đoạn này khá dồi dào. Bạn sẽ có cuộc sống dư dả và thoải mái, kế hoạch đầu tư cho kinh doanh hoặc vay mượn trở nên dễ dàng hơn. <br/>-Lời khuyên của lá bài Two of Wands là bạn nên đầu tư cho sở thích cá nhân, tận hưởng khoảng thời gian thảnh thơi trước khi mọi thứ bận rộn trở lại. <br/>-Thật may mắn khi không có bất kỳ một vấn đề nào về tiền bạc nào phát sinh trong lá bài này.',
  ),
  createCardDatas(
    '../img/TarotCard/24-Three-of-Wands.jpg',
    '-Three Of Wands phản ánh một giai đoạn của sự nghỉ ngơi. Đây không phải là thời điểm tốt để yêu đương. Tâm trạng của bạn đang đầy mâu thuẫn. <br/> -Nếu đã cảm thấy khó điều chỉnh cảm xúc, Three Of Wands khuyên bạn hãy thực hiện một chuyến đi xa. Nó sẽ mang lại cho bạn những trải nghiệm sâu sắc hơn về bản thân mình. Và bạn sẽ nhận ra mình mong muốn gì câu chuyện tình cảm. <br/>-Khi bạn đang để ý tối một người, Three Of Wands phản ánh sự thiếu quan tâm của bạn. Đối phương nghĩ rằng bạn khá hờ hững. Tuy rằng cảm xúc là thật nhưng bạn lại không biết cách thể hiện ra đến ngoài. Bạn cần phải rõ ràng hơn. Hãy bộc lộ tình cảm một cách thoải mái cũng như nói rõ về tình cảm của mình. <br/>-Nếu muốn tiến lên một một quan hệ lâu dài. Three Of Wands khuyên bạn cần dành thời gian quan tâm chăm sóc, hiểu thêm về đối phương. Trong một mối quan hệ lâu dài bạn cần xác định rõ và định hướng mối quan hệ. Và bạn cần thẳng thắn bày tỏ tình cảm cũng như định hướng của mình để đối phương hiểu rõ về bạn. <br/>-Đôi khi Three Of Wands phản ánh sự nghi hoặc của bạn về mối quan hệ. Vì quá háo hức mong chờ mà bạn nhanh chóng bước vào một mối quan hệ. Bạn nhận ra rằng mình vẫn chưa thể quen với việc phải chăm sóc lo lắng cho người khác. Bạn cần phải thả lỏng bản thân và yêu quý hiện tại của mình. <br/>',
    '-Three Of Wands tương ứng với sự bảo hộ trong tiến hành công việc. Điều này chứng tỏ các ý tưởng và phương án của bạn đang được đồng tình và ủng hộ. <br/>-Sức mạnh ổn định và quyết định đúng đắn thể hiện trạng thái của bạn. Có vẻ bạn đã sử dụng tốt những kỹ năng học được từ các giai đoạn trước. Three Of Wands đưa ra lời khuyên là cần tiếp tục nỗ lực. Dựa trên những thành quả và nền tảng trước đó. <br/>-Three Of Wands nói về một người đứng đầu dẫn dắt và có tầm nhìn. Những phẩm chất mà bạn có được chính là một yếu tố quan trọng. Đó là điều giúp bạn có thể đàm phán vào việc thúc đẩy công việc tiến lên. <br/>-Three Of Wands yêu cầu bạn cần có tầm nhìn xa. Vì ở vai trò quan trọng thì không thể đưa ra những quyết định ngắn hạn và vì lợi ích cá nhân. Nếu bạn đang được đầu tư cần tận dụng tốt những giúp đỡ tài chính mà mình đang có. Nó sẽ tạo ra những nguồn thu nhập tài chính ổn định và lâu dài cho bạn. <br/>-Và khi bạn có một vị trí tốt trong công việc thì cần phải giữ vững được vị trí hiện tại của mình. Cố gắng tận dụng mọi cơ hội để đưa công việc tiến lên. Thêm vào đó Three Of Wands cũng nhắc bạn cần tận dụng những sự giúp đỡ, mối quan hệ. Nó sẽ giúp cho dự định của bạn trở nên hoàn thiện hơn. <br/>',
    '-Three of Wands nói rằng sự lao động quá sức sẽ khiến bạn kiệt sức. Cân bằng sức khỏe là điều quan trọng phải thực hiện, không nên để cơ thể hoạt động liên tục cũng không nên ì ạch không vận động gì. <br/>-Những bài tập nhẹ, đi bộ thường xuyên rất tốt. Bạn nên thực hiện lối sống lành mạnh, ăn nhiều rau củ, đồ mát, ngủ nghỉ điều độ để tránh các căn bệnh do căng thẳng gây ra. <br/>-Ngoài ra, Three of Wands cảnh báo một số vấn đề về tình dục có thể gây ảnh hưởng xấu tới sức khỏe. <br/>',
    '-Những chuyến xả hơi, nghỉ mát là cần thiết để thư giãn nhưng bạn không nên phung phí quá nhiều ngân sách để phục vụ sở thích cá nhân. <br/>-Lá bài Three of Wands cảnh báo bạn nên tiết kiệm tiền để chuẩn bị cho tương lai. <br/>-Trong thời điểm sắp tới sẽ có những cơ hội nghề nghiệp tìm đến, việc chuẩn bị tài chính từ trước sẽ giúp bạn thuận lợi trong việc đầu tư và gọi vốn. <br/>',
  ),

]

const createOptionDatas = (name, img, color, link) => {
  return { name, img, color, link };
};

export const optionDatas = [
  createOptionDatas('Tình cảm', './img/icon/loveIcon.png', 'bg-tarot-pink', '/detail/love'),
  createOptionDatas('Sự nghiệp', './img/icon/careerIcon.png', 'bg-tarot-blue', '/detail/career'),
  createOptionDatas('Sức khỏe', './img/icon/healthIcon.png', 'bg-tarot-green', '/detail/health'),
  createOptionDatas('Tiền bạc', './img/icon/moneyIcon.png', 'bg-tarot-yellow', '/detail/money'),
]