const createCardDatas = (img, love, career, health, money) => {
  return { img, love, career, health, money };
};

export const cardDetailDatas = [
  createCardDatas(
    '../img/TarotCard/22-Ace-of-Wands.jpg',
    '-Trong tình yêu Ace Of Wands đại diện cho những ham muốn nguyên thủy về tình dục và sự thống trị. <br/>-Mối quan hệ mà bạn đang nghĩ tới chưa hẳn  là tình yêu.<br/>-Nếu bạn bỗng nhiên chú ý tới một người. Ace Of Wands cho rằng giữa hai bạn có một sự thu hút khó có thể che giấu. <br/>-Ace Of Wands cho thấy hai bạn có khả năng sẽ chấp nhận nhau. Nhưng mối quan hệ đó kéo dài bao lâu thì chưa thể biết được. <br/>-Bởi tình yêu ngoài những thời gian mãnh liệt còn có những giây phút sóng gió, thử thách mà chưa chắc ai cũng có thể vượt qua.<br/>-Ace Of Wands có sức sống mạnh mẽ và năng lượng của đam mê. Nếu nó xuất hiện nghĩa là cuộc sống của bạn đang ngập tràn sự hào hứng.<br/>',
    '-Ace Of Wands là lá bài khởi đầu của hệ gậy. Nó thể hiện về mặt tư tưởng trong việc hoạch định các vấn đề của bạn.<br/>-Sự khởi đầu của công việc trong lời tiên thể hiện hình ảnh bước đi đầu tiên trên con đường công danh.<br/>-Bạn nên tập trung vào hoạch định những bước đầu tiên cho công việc, tránh việc hăng hái mà đi quá xa vì dù sao đây mới chỉ là bước khởi đầu.<br/>-Bạn cần phải chứng tỏ với người khác năng lực của mình, cũng như rõ ràng tạo ra sự yên tâm cho người hợp tác.</br>-Cần thể hiện được tính tích cực trong suy nghĩ của mình tới mọi người xung quanh. </br>-Bạn cần phát huy tinh thần, năng lực của mình đúng lúc, tránh để bản thân bị cuốn hút bằng những thứ không quan trọng hoặc mâu thuẫn. </br>-Cần giữ sự tập trung vào công việc và những khó khăn trước mắt. </br>-Ace Of Wands khuyên bạn sử dụng tinh thần và nhiệt huyết cũng như sự chân thành để giao tiếp với đồng nghiệp khi bắt đầu công việc. </br>',
    '-Ace of Wands ám chỉ những bệnh tật di truyền từ nhiều thế hệ trong dòng họ. Bạn có thể mắc một căn bệnh di truyền từ ông bà, bố mẹ<br/-Hết sức cẩn trọng khi cơ thể có dấu hiệu lạ, những cơn dịch cúm hoặc sốt từ người thân cũng có thể lây lan nếu bạn không phòng tránh đúng cách.<br/>-Điều may mắn là tuy bệnh di truyền nhưng Ace of Wands dự báo đây không phải căn bệnh nặng, chịu khó kiêng kỵ và ăn uống điều độ bạn sẽ khỏe lại.',
    '-Ace of Wands thông báo rằng bạn có thể nhận được một khoản tiền lớn trong thời gian tới. Đó có thể là tiền thưởng cho những ý tưởng sáng tạo thông minh của bạn, bạn gần như thỏa mãn và tận hưởng thành quả của mình<br/>-Mặt khác, lá bài cho rằng số tiền bạn nhận được có thể từ một khoản thừa kế, hoặc khoản tiêu vặt lớn từ gia đình<br/>-Nhìn chung, tình hình tài chính trong thời gian tới tương đối dồi dào. Nhớ tiêu tiền đúng cách và cám ơn những người đã trao số tiền đó cho bạn.',
  ),
  createCardDatas(
    '../img/TarotCard/23-Two-of-Wands.jpg',
    '-Two Of Wands là một lá bài thuận lợi.<br/>-Nó ám chỉ một số thay đổi sắp đến trong cuộc sống của bạn và bạn sẵn sàng trong trạng thái tuyệt vời để đón nhận. <br/>-Bạn rất cố gắng trong việc hoàn thiện bản thân. Và đây là thời điểm Two Of Wands để bạn thấy được kết quả từ nỗ lực của mình. Một mối quan hệ mới sẽ nhanh chóng đến với bạn. <br/>-Tuy vậy, về sau bạn lại cảm thấy nghi ngờ về tính định hướng của mỗi quan hệ. <br/>-Trong thời gian này, Two Of Wands khuyên bạn nên xem xét kỹ lại. Những sự lựa chọn cũng như tính định hướng của cả hai trước khi bước vào mối quan hệ. <br/>-Two Of Wands là dấu hiệu của những thay đổi mới trong tình yêu của bạn. Tuy nhiên nó không hề tiêu cực.<br/> -Trong một số trường hợp, Two Of Wands còn cho thấy bạn cần đưa ra quyết định. Cũng như bạn phải tin tưởng vào định hướng của bản thân.<br/>',
    '-Two Of Wands là lá bài thứ hai trong các lá ẩn phụ bộ Gậy. Thể hiện trạng thái tiếp thu, đang vận dụng các tri thức trong việc hoạch định các kế hoạch công việc của. <br/>-Two Of Wands khuyên bạn cần tập trung học hỏi cho tốt trước khi thiết lập kế hoạch. Vì điều đó sẽ tiết kiệm được nhiều thời gian và công sức. <br/>-Nếu đang trong giai đoạn đàm phán, bạn cần kiểm soát tốt các ý tưởng của mình. <br/>-Two Of Wands hướng tới việc tiếp tục phát huy những yếu tố tích cực đã được mở đầu từ trước. Đồng thời với việc tiếp tục mở rộng sức ảnh hưởng của hoạch định ban đầu. Bạn còn phải có sự tính toán trước các bước đi tiếp theo. Để duy trì, giữ gìn sự phát triển và ổn định về thu nhập tài chính. <br/>-Đối với những mối quan hệ đang có, cần tiếp tục phát triển để có được sự ủng hộ.<br/>',
    '-Lá bài Two of Wands dự báo sự nghiệp ở đỉnh cao, tiền bạc không phải lo nghĩ chính là giai đoạn bạn phải chăm lo kỹ lưỡng cho sức khỏe. <br/>-Mọi lo âu, phiền muộn có thể diễn ra trong giai đoạn này, những vấn đề về sức khỏe đang diễn ra theo chiều hướng xấu. <br/>-Điều cần làm nhất là sinh hoạt theo một chế độ lành mạnh và khám sức khỏe định kỳ đều đặn. <br/>-Trường hợp bạn đang nhận điều trị thì phương thuốc tốt nhất là tinh thần, sự an ủi động viên từ phía gia đình sẽ giúp bạn khá hơn rất nhiều.',
    '-Đi cùng sự thành công của sự nghiệp, tiền bạc trong giai đoạn này khá dồi dào. Bạn sẽ có cuộc sống dư dả và thoải mái, kế hoạch đầu tư cho kinh doanh hoặc vay mượn trở nên dễ dàng hơn. <br/>-Lời khuyên của lá bài Two of Wands là bạn nên đầu tư cho sở thích cá nhân, tận hưởng khoảng thời gian thảnh thơi trước khi mọi thứ bận rộn trở lại. <br/>-Thật may mắn khi không có bất kỳ một vấn đề nào về tiền bạc nào phát sinh trong lá bài này.',
  ),
  createCardDatas(
    '../img/TarotCard/24-Three-of-Wands.jpg',
    '-Three Of Wands phản ánh một giai đoạn của sự nghỉ ngơi. Đây không phải là thời điểm tốt để yêu đương. Tâm trạng của bạn đang đầy mâu thuẫn. <br/> -Nếu đã cảm thấy khó điều chỉnh cảm xúc, Three Of Wands khuyên bạn hãy thực hiện một chuyến đi xa. Nó sẽ mang lại cho bạn những trải nghiệm sâu sắc hơn về bản thân mình. Và bạn sẽ nhận ra mình mong muốn gì câu chuyện tình cảm. <br/>-Khi bạn đang để ý tối một người, Three Of Wands phản ánh sự thiếu quan tâm của bạn. Đối phương nghĩ rằng bạn khá hờ hững. Tuy rằng cảm xúc là thật nhưng bạn lại không biết cách thể hiện ra đến ngoài. Bạn cần phải rõ ràng hơn. Hãy bộc lộ tình cảm một cách thoải mái cũng như nói rõ về tình cảm của mình. <br/>-Nếu muốn tiến lên một một quan hệ lâu dài. Three Of Wands khuyên bạn cần dành thời gian quan tâm chăm sóc, hiểu thêm về đối phương. Trong một mối quan hệ lâu dài bạn cần xác định rõ và định hướng mối quan hệ. Và bạn cần thẳng thắn bày tỏ tình cảm cũng như định hướng của mình để đối phương hiểu rõ về bạn. <br/>-Đôi khi Three Of Wands phản ánh sự nghi hoặc của bạn về mối quan hệ. Vì quá háo hức mong chờ mà bạn nhanh chóng bước vào một mối quan hệ. Bạn nhận ra rằng mình vẫn chưa thể quen với việc phải chăm sóc lo lắng cho người khác. Bạn cần phải thả lỏng bản thân và yêu quý hiện tại của mình. <br/>',
    '-Three Of Wands tương ứng với sự bảo hộ trong tiến hành công việc. Điều này chứng tỏ các ý tưởng và phương án của bạn đang được đồng tình và ủng hộ. <br/>-Sức mạnh ổn định và quyết định đúng đắn thể hiện trạng thái của bạn. Có vẻ bạn đã sử dụng tốt những kỹ năng học được từ các giai đoạn trước. Three Of Wands đưa ra lời khuyên là cần tiếp tục nỗ lực. Dựa trên những thành quả và nền tảng trước đó. <br/>-Three Of Wands nói về một người đứng đầu dẫn dắt và có tầm nhìn. Những phẩm chất mà bạn có được chính là một yếu tố quan trọng. Đó là điều giúp bạn có thể đàm phán vào việc thúc đẩy công việc tiến lên. <br/>-Three Of Wands yêu cầu bạn cần có tầm nhìn xa. Vì ở vai trò quan trọng thì không thể đưa ra những quyết định ngắn hạn và vì lợi ích cá nhân. Nếu bạn đang được đầu tư cần tận dụng tốt những giúp đỡ tài chính mà mình đang có. Nó sẽ tạo ra những nguồn thu nhập tài chính ổn định và lâu dài cho bạn. <br/>-Và khi bạn có một vị trí tốt trong công việc thì cần phải giữ vững được vị trí hiện tại của mình. Cố gắng tận dụng mọi cơ hội để đưa công việc tiến lên. Thêm vào đó Three Of Wands cũng nhắc bạn cần tận dụng những sự giúp đỡ, mối quan hệ. Nó sẽ giúp cho dự định của bạn trở nên hoàn thiện hơn. <br/>',
    '-Three of Wands nói rằng sự lao động quá sức sẽ khiến bạn kiệt sức. Cân bằng sức khỏe là điều quan trọng phải thực hiện, không nên để cơ thể hoạt động liên tục cũng không nên ì ạch không vận động gì. <br/>-Những bài tập nhẹ, đi bộ thường xuyên rất tốt. Bạn nên thực hiện lối sống lành mạnh, ăn nhiều rau củ, đồ mát, ngủ nghỉ điều độ để tránh các căn bệnh do căng thẳng gây ra. <br/>-Ngoài ra, Three of Wands cảnh báo một số vấn đề về tình dục có thể gây ảnh hưởng xấu tới sức khỏe. <br/>',
    '-Những chuyến xả hơi, nghỉ mát là cần thiết để thư giãn nhưng bạn không nên phung phí quá nhiều ngân sách để phục vụ sở thích cá nhân. <br/>-Lá bài Three of Wands cảnh báo bạn nên tiết kiệm tiền để chuẩn bị cho tương lai. <br/>-Trong thời điểm sắp tới sẽ có những cơ hội nghề nghiệp tìm đến, việc chuẩn bị tài chính từ trước sẽ giúp bạn thuận lợi trong việc đầu tư và gọi vốn. <br/>',
  ),
]

const createOptionDatas = (name, img, color, link) => {
  return { name, img, color, link };
};

export const optionDatas = [
  createOptionDatas('Tình cảm', './img/icon/loveIcon.png', 'bg-tarot-pink', '/detail/love'),
  createOptionDatas('Sự nghiệp', './img/icon/careerIcon.png', 'bg-tarot-blue', '/detail/career'),
  createOptionDatas('Sức khỏe', './img/icon/healthIcon.png', 'bg-tarot-green', '/detail/health'),
  createOptionDatas('Tiền bạc', './img/icon/moneyIcon.png', 'bg-tarot-yellow', '/detail/money'),
]